import {
  BarChart3,
  Bell,
  BookOpen,
  DollarSign,
  FileText,
  Inbox,
  Megaphone,
  Settings,
  Tags,
  Upload,
  Users,
  Wrench,
} from 'lucide-react';

import { expandLegacyPropertyPermissionIds } from '@/features/dashboard/team/lib/legacyPermissionExpansion';
import type { TeamPermission } from '@/features/dashboard/team/types/propertyTeam';

export const PROPERTY_ADMIN_ROLE_ID = 'ADMIN' as const;

export const TEAM_PERMISSIONS: TeamPermission[] = [
  {
    id: 'bookings:view',
    name: 'View Bookings',
    description: 'View booking list and detail',
    category: 'Bookings',
    icon: BookOpen,
  },
  {
    id: 'bookings.create:add',
    name: 'Create booking',
    description: 'New booking',
    category: 'Bookings',
    icon: BookOpen,
  },
  {
    id: 'bookings.import:add',
    name: 'Import bookings',
    description: 'CSV booking import',
    category: 'Bookings',
    icon: Upload,
  },
  {
    id: 'bookings.detail.stay:edit',
    name: 'Edit stay',
    description: 'Stay tab fields',
    category: 'Bookings',
    icon: BookOpen,
  },
  {
    id: 'bookings.detail.guests:edit',
    name: 'Edit guests',
    description: 'Guests tab and Valid ID docs',
    category: 'Bookings',
    icon: BookOpen,
  },
  {
    id: 'bookings.detail.parking:edit',
    name: 'Edit parking',
    description: 'Parking tab',
    category: 'Bookings',
    icon: BookOpen,
  },
  {
    id: 'bookings.detail.pets:edit',
    name: 'Edit pets',
    description: 'Pets tab',
    category: 'Bookings',
    icon: BookOpen,
  },
  {
    id: 'bookings.detail.pricing:edit',
    name: 'Edit booking pricing',
    description: 'Pricing tab on detail',
    category: 'Bookings',
    icon: BookOpen,
  },
  {
    id: 'bookings.detail.workflow:edit',
    name: 'Run workflow',
    description: 'Transitions and automation',
    category: 'Bookings',
    icon: BookOpen,
  },
  {
    id: 'finance:view',
    name: 'View Finance',
    description: 'View finance dashboard and stays',
    category: 'Finance',
    icon: DollarSign,
  },
  {
    id: 'finance.transactions:add',
    name: 'Add transaction',
    description: 'Create finance line items',
    category: 'Finance',
    icon: DollarSign,
  },
  {
    id: 'finance.transactions:edit',
    name: 'Edit transaction',
    description: 'Update finance line items',
    category: 'Finance',
    icon: DollarSign,
  },
  {
    id: 'finance.transactions:delete',
    name: 'Delete transaction',
    description: 'Delete finance line items',
    category: 'Finance',
    icon: DollarSign,
  },
  {
    id: 'finance.export:view',
    name: 'Export finance',
    description: 'Download finance reports',
    category: 'Finance',
    icon: DollarSign,
  },
  {
    id: 'pricing:view',
    name: 'View Pricing',
    description: 'View nightly rates and fee defaults',
    category: 'Pricing',
    icon: Tags,
  },
  {
    id: 'pricing.rates:edit',
    name: 'Edit rates',
    description: 'Rates, fees, and date overrides',
    category: 'Pricing',
    icon: Tags,
  },
  {
    id: 'pricing.blocks:add',
    name: 'Block dates',
    description: 'Block availability dates',
    category: 'Pricing',
    icon: Tags,
  },
  {
    id: 'pricing.blocks:delete',
    name: 'Unblock dates',
    description: 'Remove availability blocks',
    category: 'Pricing',
    icon: Tags,
  },
  {
    id: 'pricing.channels:view',
    name: 'View channel sync',
    description: 'View connected Airbnb / OTA calendars',
    category: 'Pricing',
    icon: Tags,
  },
  {
    id: 'pricing.channels:edit',
    name: 'Manage channel sync',
    description: 'Connect, edit, and sync Airbnb / OTA calendars',
    category: 'Pricing',
    icon: Tags,
  },
  {
    id: 'maintenance:view',
    name: 'View Maintenance',
    description: 'View upkeep reminders',
    category: 'Maintenance',
    icon: Wrench,
  },
  {
    id: 'maintenance.reminders:add',
    name: 'Add reminder',
    description: 'Create maintenance reminders',
    category: 'Maintenance',
    icon: Wrench,
  },
  {
    id: 'maintenance.reminders:edit',
    name: 'Edit reminder',
    description: 'Update maintenance reminders',
    category: 'Maintenance',
    icon: Wrench,
  },
  {
    id: 'maintenance.reminders:delete',
    name: 'Delete reminder',
    description: 'Delete maintenance reminders',
    category: 'Maintenance',
    icon: Wrench,
  },
  {
    id: 'maintenance.export:view',
    name: 'Export maintenance',
    description: 'Download maintenance reports',
    category: 'Maintenance',
    icon: Wrench,
  },
  {
    id: 'marketing:view',
    name: 'View Marketing',
    description: 'Content Studio read access',
    category: 'Marketing',
    icon: Megaphone,
  },
  {
    id: 'marketing.content:add',
    name: 'Add content',
    description: 'Create calendar, design, or video content',
    category: 'Marketing',
    icon: Megaphone,
  },
  {
    id: 'marketing.content:edit',
    name: 'Edit content',
    description: 'Edit and autosave marketing content',
    category: 'Marketing',
    icon: Megaphone,
  },
  {
    id: 'marketing.templates:add',
    name: 'Add marketing template',
    description: 'Save custom marketing templates',
    category: 'Marketing',
    icon: Megaphone,
  },
  {
    id: 'marketing.templates:edit',
    name: 'Edit marketing template',
    description: 'Rename or move saved templates',
    category: 'Marketing',
    icon: Megaphone,
  },
  {
    id: 'marketing.templates:delete',
    name: 'Delete marketing template',
    description: 'Remove saved marketing templates',
    category: 'Marketing',
    icon: Megaphone,
  },
  {
    id: 'marketing.generate:add',
    name: 'Generate with AI',
    description: 'AI calendar, design, and video generation',
    category: 'Marketing',
    icon: Megaphone,
  },
  {
    id: 'marketing.generate.video:add',
    name: 'Generate AI video',
    description: 'AI video generation on the Generate tab (separate from cheaper image generation)',
    category: 'Marketing',
    icon: Megaphone,
  },
  {
    id: 'marketing.publish:add',
    name: 'Publish to Meta',
    description: 'Publish to Facebook or Instagram',
    category: 'Marketing',
    icon: Megaphone,
  },
  {
    id: 'notifications:view',
    name: 'View Notifications',
    description: 'View Telegram module settings',
    category: 'Notifications',
    icon: Bell,
  },
  {
    id: 'notifications.chat:edit',
    name: 'Edit chat Telegram',
    description: 'Chat module bots and schedules',
    category: 'Notifications',
    icon: Bell,
  },
  {
    id: 'notifications.marketing:edit',
    name: 'Edit marketing Telegram',
    description: 'Marketing module bots and schedules',
    category: 'Notifications',
    icon: Bell,
  },
  {
    id: 'notifications.staff:edit',
    name: 'Edit staff Telegram',
    description: 'Staff module bots and schedules',
    category: 'Notifications',
    icon: Bell,
  },
  {
    id: 'notifications.operations:edit',
    name: 'Edit operations Telegram',
    description: 'Operations module bots and schedules',
    category: 'Notifications',
    icon: Bell,
  },
  {
    id: 'notifications.finance:edit',
    name: 'Edit finance Telegram',
    description: 'Finance module bots and schedules',
    category: 'Notifications',
    icon: Bell,
  },
  {
    id: 'notifications.maintenance:edit',
    name: 'Edit maintenance Telegram',
    description: 'Maintenance module bots and schedules',
    category: 'Notifications',
    icon: Bell,
  },
  {
    id: 'templates:view',
    name: 'View Templates',
    description: 'View email templates',
    category: 'Templates',
    icon: FileText,
  },
  {
    id: 'templates.standard:edit',
    name: 'Edit standard templates',
    description: 'House rules / check-in/out / parking reminders',
    category: 'Templates',
    icon: FileText,
  },
  {
    id: 'templates.email:edit',
    name: 'Edit email templates',
    description: 'Workflow email templates',
    category: 'Templates',
    icon: FileText,
  },
  {
    id: 'templates.custom:add',
    name: 'Add custom template',
    description: 'Create custom templates',
    category: 'Templates',
    icon: FileText,
  },
  {
    id: 'templates.custom:edit',
    name: 'Edit custom template',
    description: 'Update custom templates',
    category: 'Templates',
    icon: FileText,
  },
  {
    id: 'templates.custom:delete',
    name: 'Delete custom template',
    description: 'Remove custom templates',
    category: 'Templates',
    icon: FileText,
  },
  {
    id: 'publicPages:view',
    name: 'View Public Pages',
    description: 'View listing and stay guide editors',
    category: 'Public Pages',
    icon: FileText,
  },
  {
    id: 'publicPages.property:edit',
    name: 'Edit property page',
    description: 'Listing page layout and shell',
    category: 'Public Pages',
    icon: FileText,
  },
  {
    id: 'publicPages.stayGuide:edit',
    name: 'Edit stay guide page',
    description: 'Stay guide page layout and shell',
    category: 'Public Pages',
    icon: FileText,
  },
  {
    id: 'publicPages.showcase:edit',
    name: 'Edit showcase page',
    description: 'Showcase landing page templates and sections',
    category: 'Public Pages',
    icon: FileText,
  },
  {
    id: 'settings:view',
    name: 'View Settings',
    description: 'View property settings',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.integrations:view',
    name: 'View integrations',
    description: 'Read-only integrations section',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.basicInfo:edit',
    name: 'Edit basic info',
    description: 'Name, contact, brand color',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.media:edit',
    name: 'Edit photos & videos',
    description: 'Property media gallery',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.propertyDetails:edit',
    name: 'Edit property details',
    description: 'Capacity, unit type, check-in times',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.amenities:edit',
    name: 'Edit amenities',
    description: 'Amenity presets and custom items',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.houseRules:edit',
    name: 'Edit house rules',
    description: 'House rule presets and custom items',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.guestForm:edit',
    name: 'Edit guest form',
    description: 'Pets, parking, surprise decor toggles',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.cancellationPolicy:edit',
    name: 'Edit cancellation policy',
    description: 'Cancellation policy text',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.location:edit',
    name: 'Edit location',
    description: 'Address and map fields',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.socials:edit',
    name: 'Edit socials',
    description: 'Social links and reviews',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.payment:edit',
    name: 'Edit payment',
    description: 'Payment methods (OTP required)',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.buildingForms:edit',
    name: 'Edit building forms',
    description: 'GAF owner fields',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.emailAutomations:edit',
    name: 'Edit email automations',
    description: 'Reply-to and automation toggles',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.voiceReceptionist:edit',
    name: 'Edit voice receptionist',
    description: 'AI voice receptionist settings',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.aiOverrides:edit',
    name: 'Edit AI overrides',
    description: 'Property AI platform overrides',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'settings.dangerZone:edit',
    name: 'Archive / restore',
    description: 'Archive or restore property (not delete)',
    category: 'Settings',
    icon: Settings,
  },
  {
    id: 'team:view',
    name: 'View Team',
    description: 'View team members',
    category: 'Team',
    icon: Users,
  },
  {
    id: 'team.invitations:add',
    name: 'Invite members',
    description: 'Send property invitations',
    category: 'Team',
    icon: Users,
  },
  {
    id: 'team.invitations:edit',
    name: 'Resend invitations',
    description: 'Resend pending invitations',
    category: 'Team',
    icon: Users,
  },
  {
    id: 'team.invitations:delete',
    name: 'Cancel invitations',
    description: 'Cancel pending invitations',
    category: 'Team',
    icon: Users,
  },
  {
    id: 'team.members:edit',
    name: 'Edit members',
    description: 'Change member roles and permissions',
    category: 'Team',
    icon: Users,
  },
  {
    id: 'team.members:delete',
    name: 'Remove members',
    description: 'Deactivate or remove team members',
    category: 'Team',
    icon: Users,
  },
  {
    id: 'team.customRoles:add',
    name: 'Add custom roles',
    description: 'Create custom roles',
    category: 'Team',
    icon: Users,
  },
  {
    id: 'team.customRoles:edit',
    name: 'Edit custom roles',
    description: 'Update custom roles',
    category: 'Team',
    icon: Users,
  },
  {
    id: 'team.customRoles:delete',
    name: 'Delete custom roles',
    description: 'Remove custom roles',
    category: 'Team',
    icon: Users,
  },
  {
    id: 'inbox:view',
    name: 'View Inbox',
    description: 'View guest inbox threads',
    category: 'Inbox',
    icon: Inbox,
  },
  {
    id: 'inbox.messages:edit',
    name: 'Reply Inbox',
    description: 'Send replies and AI suggest',
    category: 'Inbox',
    icon: Inbox,
  },
  {
    id: 'inbox.channels:add',
    name: 'Connect channels',
    description: 'Connect Meta inbox channels',
    category: 'Inbox',
    icon: Inbox,
  },
  {
    id: 'inbox.channels:delete',
    name: 'Disconnect channels',
    description: 'Disconnect Meta inbox channels',
    category: 'Inbox',
    icon: Inbox,
  },
  {
    id: 'inbox.quickReplies:add',
    name: 'Add quick replies',
    description: 'Create quick reply templates',
    category: 'Inbox',
    icon: Inbox,
  },
  {
    id: 'inbox.quickReplies:edit',
    name: 'Edit quick replies',
    description: 'Update quick reply templates',
    category: 'Inbox',
    icon: Inbox,
  },
  {
    id: 'inbox.quickReplies:delete',
    name: 'Delete quick replies',
    description: 'Remove quick reply templates',
    category: 'Inbox',
    icon: Inbox,
  },
  {
    id: 'inbox.automation:edit',
    name: 'Edit inbox automation',
    description: 'AI tone, rules, and auto-send',
    category: 'Inbox',
    icon: Inbox,
  },
  {
    id: 'analytics:view',
    name: 'View Analytics',
    description: 'View performance KPIs, forward view, and the AI review',
    category: 'Analytics',
    icon: BarChart3,
  },
  {
    id: 'analytics:export',
    name: 'Export Analytics',
    description: 'Download the property Analytics PDF report',
    category: 'Analytics',
    icon: BarChart3,
  },
];

/** Seeded template grants (Phase 3–6 leaves). */
export const SEEDED_TEMPLATE_PERMISSIONS: Record<string, string[]> = {
  'Full Access': TEAM_PERMISSIONS.map((permission) => permission.id),
  Operations: [
    'bookings:view',
    'bookings.create:add',
    'bookings.detail.stay:edit',
    'bookings.detail.guests:edit',
    'bookings.detail.parking:edit',
    'bookings.detail.pets:edit',
    'bookings.detail.pricing:edit',
    'bookings.detail.workflow:edit',
    'maintenance:view',
    'maintenance.reminders:add',
    'maintenance.reminders:edit',
    'maintenance.reminders:delete',
    'maintenance.export:view',
    'notifications:view',
    'templates:view',
    'publicPages:view',
    'pricing:view',
    'pricing.channels:view',
    'pricing.channels:edit',
    'inbox:view',
    'inbox.messages:edit',
    'marketing:view',
    'marketing.content:add',
    'marketing.content:edit',
    'marketing.templates:add',
    'marketing.templates:edit',
    'marketing.templates:delete',
    'marketing.generate:add',
    'marketing.generate.video:add',
    'marketing.publish:add',
    'analytics:view',
  ],
  'Read Only': [
    'bookings:view',
    'maintenance:view',
    'notifications:view',
    'templates:view',
    'publicPages:view',
    'pricing:view',
    'pricing.channels:view',
    'team:view',
    'inbox:view',
    'analytics:view',
  ],
};

export const PERMISSION_CATEGORIES = [...new Set(TEAM_PERMISSIONS.map((p) => p.category))];

export function isPropertyAdminRoleId(roleId: string): boolean {
  return roleId === PROPERTY_ADMIN_ROLE_ID;
}

/** Normalize + expand legacy Phase 3–6 umbrella ids for client-side checks. */
export function normalizeClientPermissionIds(raw: readonly string[] | undefined): string[] {
  if (!raw?.length) return [];
  return expandLegacyPropertyPermissionIds(raw);
}
