#!/usr/bin/env bash
# GitHub Actions / CI entrypoint for Supabase deploy.
# Usage: ./scripts/deploy/ci-deploy.sh <dev|prod> [-- db-only | --functions-only | ...]
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=scripts/deploy/ci-deploy-lib.sh
source "$ROOT/scripts/deploy/ci-deploy-lib.sh"

usage() {
  cat <<'EOF'
Usage: ./scripts/deploy/ci-deploy.sh <dev|prod> [deploy options...]

Environment:
  SUPABASE_ACCESS_TOKEN     Supabase personal access token
  SUPABASE_PROJECT_REF      Target project
  LEGACY_PROD_PROJECT_REF   Deny-list ref (LEGACY, e.g. zftt…) — required in CI
  DEPLOY_CONFIRM=dev|prod   Non-interactive confirm matching the target
  CI=1                      Set automatically in GitHub Actions

Optional passthrough flags after `--`:
  --db-only, --functions-only, --no-include-all

Dev passes --allow-multi-tenancy and --include-all. Production uses strict
migration order and refuses the legacy project ref.

Example (GitHub Actions):
  env:
    CI: "1"
    DEPLOY_CONFIRM: dev
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    LEGACY_PROD_PROJECT_REF: ${{ secrets.LEGACY_PROD_PROJECT_REF }}
  run: ./scripts/deploy/ci-deploy.sh dev
EOF
}

TARGET="${1:-}"
shift || true

if [[ "$TARGET" != "dev" && "$TARGET" != "prod" ]]; then
  echo "ERROR: target must be dev or prod (got '${TARGET:-}')." >&2
  usage >&2
  exit 1
fi

if [[ "${1:-}" == "--" ]]; then
  shift
fi

ci_deploy_require_env SUPABASE_ACCESS_TOKEN
ci_deploy_require_env SUPABASE_PROJECT_REF
ci_deploy_require_env LEGACY_PROD_PROJECT_REF

export CI="${CI:-1}"
export DEPLOY_CONFIRM="${DEPLOY_CONFIRM:-$TARGET}"

ci_deploy_assert_not_legacy_ref "$SUPABASE_PROJECT_REF" "$LEGACY_PROD_PROJECT_REF"

echo "CI deploy target: $(ci_deploy_mask_ref "$SUPABASE_PROJECT_REF")"
echo "Legacy deny-list: $(ci_deploy_mask_ref "$LEGACY_PROD_PROJECT_REF")"

# Ephemeral env for deploy/backup classification on CI runners (no committed secrets).
ENV_FILE="$ROOT/supabase/.env.dev.local"
cat >"$ENV_FILE" <<EOF
# Generated by ci-deploy.sh — ephemeral on CI runners only
DEV_PROJECT_REF=$([[ "$TARGET" == "dev" ]] && printf '%s' "$SUPABASE_PROJECT_REF" || printf '%s' "${MULTI_TENANT_DEV_PROJECT_REF:-}")
PROD_PROJECT_REF=$([[ "$TARGET" == "prod" ]] && printf '%s' "$SUPABASE_PROJECT_REF" || printf '%s' "$LEGACY_PROD_PROJECT_REF")
DEV_SUPABASE_URL=$([[ "$TARGET" == "dev" ]] && printf 'https://%s.supabase.co' "$SUPABASE_PROJECT_REF" || true)
DEV_SERVICE_ROLE_KEY=ci-placeholder-not-used-for-db-push
EOF

export SUPABASE_ACCESS_TOKEN

if [[ "$TARGET" == "dev" ]]; then
  exec "$ROOT/scripts/deploy/deploy-supabase-dev.sh" --allow-multi-tenancy --include-all "$@"
fi

echo "→ supabase link --project-ref $(ci_deploy_mask_ref "$SUPABASE_PROJECT_REF")"
"$ROOT/scripts/dev/bunx" --bun supabase@latest link --project-ref "$SUPABASE_PROJECT_REF" >/dev/null
exec "$ROOT/scripts/deploy/deploy-supabase.sh" --allow-multi-tenancy "$@"
