import { c } from '../theme';
import {
  BookingFlowScreen,
  PricingScreen,
  ReceiptCheckScreen,
  SyncCalendarScreen,
} from './bookingScreens';
import { makeFeatureConcept, type FeatureSpec } from './concept';
import { ContentStudioScreen, InsightsScreen } from './growthScreens';
import { BookingSiteScreen, ReceptionistScreen } from './guestScreens';
import { AiModeScreen, AlertsScreen, MaintenanceScreen, TeamScreen } from './opsScreens';

/**
 * Feature series: one piece per dashboard module. Order is the showcase order.
 * Each spec renders to out/features/<nn>-<slug>/ (stills per format + videos).
 */
export const featureSpecs: FeatureSpec[] = [
  {
    slug: '01-bookings',
    module: 'Bookings',
    tone: 'paper',
    tall: ['Bookings', 'that run', 'themselves.'],
    wide: ['Bookings that', 'run themselves.'],
    accentTall: 2,
    accentWide: 1,
    sub: 'Forms, receipts, approvals and guest emails move each stay forward on their own.',
    screenBg: c.paper,
    screen: (f, s) => <BookingFlowScreen frame={f} startAt={s} />,
    video: 190,
  },
  {
    slug: '02-receipt-check',
    module: 'AI receipt check',
    tone: 'night',
    tall: ['Receipts,', 'checked', 'for you.'],
    wide: ['Receipts,', 'checked for you.'],
    accentTall: 1,
    accentWide: 1,
    sub: 'AI reads each payment receipt and matches the amount, reference and date to the booking.',
    screenBg: c.paper,
    screen: (f, s) => <ReceiptCheckScreen frame={f} startAt={s} />,
    video: 180,
  },
  {
    slug: '03-channel-sync',
    module: 'Channel sync',
    tone: 'white',
    tall: ['Airbnb and', 'direct.', 'One calendar.'],
    wide: ['Airbnb and direct.', 'One calendar.'],
    accentTall: 2,
    accentWide: 1,
    sub: 'Bookings and blocked dates sync both ways, so a night is never sold twice.',
    screenBg: c.paper,
    screen: (f, s) => <SyncCalendarScreen frame={f} startAt={s} />,
    video: 170,
  },
  {
    slug: '04-smart-pricing',
    module: 'Smart Pricing',
    tone: 'brand',
    tall: ['A rate for', 'every', 'night.'],
    wide: ['A rate for', 'every night.'],
    accentTall: 1,
    accentWide: 1,
    sub: 'Set rates by hand, or let AI suggest a rate for each night.',
    screenBg: c.paper,
    screen: (f, s) => <PricingScreen frame={f} startAt={s} />,
    video: 180,
  },
  {
    slug: '05-ai-receptionist',
    module: 'AI receptionist',
    tone: 'tint',
    tall: ['Guests call.', 'Kame', 'answers.'],
    wide: ['Guests call.', 'Kame answers.'],
    accentTall: 1,
    accentWide: 1,
    sub: 'Questions about parking, check-in and house rules get answered day or night.',
    screenBg: c.night,
    screen: (f, s) => <ReceptionistScreen frame={f} startAt={s} />,
    video: 190,
  },
  {
    slug: '06-booking-site',
    module: 'Booking site',
    tone: 'graphite',
    tall: ['Guests', 'book', 'direct.'],
    wide: ['Guests book', 'direct.'],
    accentTall: 1,
    accentWide: 1,
    sub: 'Your own booking page with live dates, prices and the guest form built in.',
    screenBg: c.white,
    screen: (f, s) => <BookingSiteScreen frame={f} startAt={s} />,
    video: 170,
  },
  {
    slug: '07-content-studio',
    module: 'Content Studio',
    tone: 'paper',
    tall: ['Posts that', 'look like', 'your place.'],
    wide: ['Posts that look', 'like your place.'],
    accentTall: 2,
    accentWide: 1,
    sub: 'Add your photos, describe the post, and publish to Facebook and Instagram.',
    screenBg: c.paper,
    screen: (f, s) => <ContentStudioScreen frame={f} startAt={s} />,
    video: 180,
  },
  {
    slug: '08-insights',
    module: 'Insights',
    tone: 'white',
    tall: ['Numbers', 'that tell you', 'what to do.'],
    wide: ['Numbers that tell', 'you what to do.'],
    accentTall: 2,
    accentWide: 1,
    sub: 'Occupancy, rates and guest trends, with plain tips on what to improve.',
    screenBg: c.paper,
    screen: (f, s) => <InsightsScreen frame={f} startAt={s} />,
    video: 160,
  },
  {
    slug: '09-team',
    module: 'Team',
    tone: 'brand',
    tall: ['Your team.', 'Your', 'rules.'],
    wide: ['Your team.', 'Your rules.'],
    accentTall: 1,
    accentWide: 1,
    sub: 'Invite cleaners, co-hosts and staff. Choose what each person can see and do.',
    screenBg: c.paper,
    screen: (f, s) => <TeamScreen frame={f} startAt={s} />,
    video: 160,
  },
  {
    slug: '10-maintenance',
    module: 'Maintenance',
    tone: 'tint',
    tall: ['Upkeep,', 'on', 'schedule.'],
    wide: ['Upkeep,', 'on schedule.'],
    accentTall: 1,
    accentWide: 1,
    sub: 'Recurring tasks, reminders and a clear done list for every unit.',
    screenBg: c.paper,
    screen: (f, s) => <MaintenanceScreen frame={f} startAt={s} />,
    video: 160,
  },
  {
    slug: '11-telegram-alerts',
    module: 'Telegram alerts',
    tone: 'paper',
    tall: ['Your team', 'hears it', 'first.'],
    wide: ['Your team', 'hears it first.'],
    accentTall: 1,
    accentWide: 1,
    sub: 'New bookings, guest messages and maintenance go to the right Telegram group.',
    screenBg: c.night,
    screen: (f, s) => <AlertsScreen frame={f} startAt={s} />,
    video: 170,
  },
  {
    slug: '12-ai-mode',
    module: 'AI mode',
    tone: 'night',
    tall: ['Just ask.', 'It knows', 'your numbers.'],
    wide: ['Ask about', 'your rentals.'],
    accentTall: 1,
    accentWide: 1,
    sub: 'Ask in plain words. Answers come from your live bookings and finance.',
    screenBg: c.paper,
    screen: (f, s) => <AiModeScreen frame={f} startAt={s} />,
    video: 200,
  },
];

export const features = featureSpecs.map((spec) => ({ spec, Concept: makeFeatureConcept(spec) }));
