#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
git reset HEAD >/dev/null 2>&1 || true

c() { git commit -m "$MSG"; }

MSG="$(cat <<'EOF'
feat(ui): polish activity log ui and filters
EOF
)"
git add -- 'ui/src/features/dashboard/activity/components/ActivityCategoryChips.tsx' 'ui/src/features/dashboard/activity/components/ActivityDetailSheet.tsx' 'ui/src/features/dashboard/activity/components/ActivityFeedList.tsx' 'ui/src/features/dashboard/activity/components/ActivityFilters.tsx' 'ui/src/features/dashboard/activity/components/ActivityLogPanel.tsx' 'ui/src/features/dashboard/activity/components/ActivityRow.tsx' 'ui/src/features/dashboard/activity/components/ActivitySettingsSection.tsx' 'ui/src/features/dashboard/activity/lib/activityCatalog.test.ts' 'ui/src/features/dashboard/activity/lib/activityFilterUtils.ts' 'ui/src/features/dashboard/activity/lib/activityFormat.test.ts' 'ui/src/features/dashboard/activity/lib/activityFormat.ts' 'ui/src/features/dashboard/ai-assistant/components/AiAssistantLauncherButton.tsx' 'ui/src/features/dashboard/ai-assistant/components/blocks/TextBlock.tsx' 'ui/src/features/dashboard/ai-assistant/hooks/useAiAssistantAccess.ts' 'ui/src/features/dashboard/ai-assistant/hooks/useAiAssistantChat.ts' 'ui/src/features/dashboard/ai-assistant/hooks/useAiAssistantConversations.ts' 'ui/src/features/dashboard/ai-assistant/hooks/useAiDashboardAssistantSettings.ts' 'ui/src/features/dashboard/ai-assistant/lib/aiAssistantApi.ts' 'ui/src/features/dashboard/ai-assistant/lib/assistantFabLayout.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/assistantFabLayout.ts' 'ui/src/features/dashboard/ai-assistant/lib/assistantOpenStore.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/assistantStream.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/assistantStream.ts' 'ui/src/features/dashboard/ai-assistant/lib/assistantToolLabels.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/attachedContext.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/bookingPickerItems.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/chatAttachments.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/chatBlockDisplay.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/contextPickerCatalogVisual.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/contextPickerRegistry.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/conversationTitle.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/dynamicFormValidation.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/humanizeAssistantLabels.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/moduleSuggestions.test.ts' 'ui/src/features/dashboard/ai-assistant/lib/partitionAssistantBlocks.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): extend ai assistant tests and fab layout
EOF
)"
git add -- 'ui/src/features/dashboard/ai-assistant/lib/speechRecognition.test.ts' 'ui/src/features/dashboard/analytics/components/AiPerformanceReviewCard.tsx' 'ui/src/features/dashboard/analytics/components/AnalyticsDistributionCard.tsx' 'ui/src/features/dashboard/analytics/components/AnalyticsGuestSignalsCard.tsx' 'ui/src/features/dashboard/analytics/components/AnalyticsOverviewSection.tsx' 'ui/src/features/dashboard/analytics/components/BenchmarkCard.tsx' 'ui/src/features/dashboard/analytics/components/GuestAgeCard.tsx' 'ui/src/features/dashboard/analytics/components/GuestPartySizeCard.tsx' 'ui/src/features/dashboard/analytics/components/OrgAnalyticsKpiCards.tsx' 'ui/src/features/dashboard/analytics/components/OrgPropertyComparisonTable.tsx' 'ui/src/features/dashboard/analytics/components/PlaybookList.tsx' 'ui/src/features/dashboard/analytics/hooks/useAnalyticsAiReview.ts' 'ui/src/features/dashboard/analytics/hooks/useAnalyticsApi.ts' 'ui/src/features/dashboard/analytics/lib/aiReviewTypes.ts' 'ui/src/features/dashboard/analytics/lib/analyticsDateRange.test.ts' 'ui/src/features/dashboard/analytics/lib/analyticsPeriod.test.ts' 'ui/src/features/dashboard/analytics/lib/exportCsv.test.ts' 'ui/src/features/dashboard/analytics/lib/exportCsv.ts' 'ui/src/features/dashboard/analytics/lib/types.ts' 'ui/src/features/dashboard/analytics/pages/OrgAnalyticsPage.tsx' 'ui/src/features/dashboard/analytics/pages/PropertyAnalyticsPage.tsx' 'ui/src/features/dashboard/analytics/components/AiPerformanceReviewGeneratingStage.tsx' 'ui/src/features/dashboard/analytics/components/OrgAnalyticsListingCard.tsx' 'ui/src/features/dashboard/analytics/components/OrgAnalyticsListingParts.tsx' 'ui/src/features/dashboard/analytics/components/OrgAnalyticsListingsSection.tsx' 'ui/src/features/dashboard/analytics/components/OrgAnalyticsListingsTable.tsx' 'ui/src/features/dashboard/analytics/lib/aiReviewDeepLink.test.ts' 'ui/src/features/dashboard/analytics/lib/aiReviewDeepLink.ts' 'ui/src/features/dashboard/analytics/lib/aiReviewPeriod.test.ts' 'ui/src/features/dashboard/analytics/lib/aiReviewPeriod.ts' 'ui/src/features/dashboard/analytics/lib/orgAnalyticsListings.test.ts' 'ui/src/features/dashboard/analytics/lib/orgAnalyticsListings.ts' 'ui/src/features/dashboard/analytics/lib/orgPortfolioLabels.ts' 'ui/src/features/dashboard/analytics/lib/orgPortfolioRollup.test.ts' 'ui/src/features/dashboard/analytics/lib/playbookReveal.ts'
c

MSG="$(cat <<'EOF'
feat(ui): add analytics org portfolio redesign
EOF
)"
git add -- 'ui/src/features/dashboard/announcements/components/HostAnnouncementCard.tsx' 'ui/src/features/dashboard/announcements/components/HostAnnouncementEditor.tsx' 'ui/src/features/dashboard/announcements/hooks/useHostAnnouncementReadState.ts' 'ui/src/features/dashboard/announcements/lib/hostAnnouncementDetail.test.ts' 'ui/src/features/dashboard/announcements/lib/hostAnnouncementPresentation.test.ts' 'ui/src/features/dashboard/announcements/lib/hostAnnouncementReadState.test.ts' 'ui/src/features/dashboard/announcements/lib/hostAnnouncementReadState.ts' 'ui/src/features/dashboard/announcements/lib/hostAnnouncementSchedule.test.ts' 'ui/src/features/dashboard/announcements/lib/hostAnnouncementTypes.test.ts' 'ui/src/features/dashboard/announcements/lib/hostAnnouncementsPaths.test.ts' 'ui/src/features/dashboard/bookings/components/AdminLayout.tsx' 'ui/src/features/dashboard/bookings/components/AdminListToolbar.tsx' 'ui/src/features/dashboard/bookings/components/AdminMoreSheet.tsx' 'ui/src/features/dashboard/bookings/components/AdminNewBookingModal.tsx' 'ui/src/features/dashboard/bookings/components/AdminSectionNavLayout.tsx' 'ui/src/features/dashboard/bookings/components/BookingCardGrid.tsx' 'ui/src/features/dashboard/bookings/components/BookingEditForm.tsx' 'ui/src/features/dashboard/bookings/components/BuildingFormsSettingsSection.tsx' 'ui/src/features/dashboard/bookings/components/PropertySettingsCard.tsx' 'ui/src/features/dashboard/bookings/components/TelegramAdminSettingsCard.tsx' 'ui/src/features/dashboard/bookings/components/TelegramChatSettingsCard.tsx' 'ui/src/features/dashboard/bookings/components/TelegramMarketingSettingsCard.tsx' 'ui/src/features/dashboard/bookings/components/TelegramStaffSettingsCard.tsx' 'ui/src/features/dashboard/bookings/components/property-templates/AddCustomTemplateDialog.tsx' 'ui/src/features/dashboard/bookings/components/property-templates/PropertyTemplateEditorCard.tsx' 'ui/src/features/dashboard/bookings/components/telegram-notifications/TelegramGlobalBotTokenCard.tsx' 'ui/src/features/dashboard/bookings/components/telegram-notifications/TelegramSingleTemplateSettingsCard.tsx' 'ui/src/features/dashboard/bookings/components/telegram-notifications/TelegramTemplatesManageDialog.tsx' 'ui/src/features/dashboard/bookings/components/workflow-panel/WorkflowPanel.tsx' 'ui/src/features/dashboard/bookings/hooks/useAppSettings.ts' 'ui/src/features/dashboard/bookings/hooks/useTelegramNotificationModuleBase.ts' 'ui/src/features/dashboard/bookings/hooks/useUploadAppSettingsAsset.ts' 'ui/src/features/dashboard/bookings/hooks/useVoiceReceptionistSettings.ts' 'ui/src/features/dashboard/bookings/lib/adminBottomNav.test.ts' 'ui/src/features/dashboard/bookings/lib/adminGuestSlots.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): update property analytics and ai review
EOF
)"
git add -- 'ui/src/features/dashboard/bookings/lib/adminLayoutFillMain.test.ts' 'ui/src/features/dashboard/bookings/lib/adminNavPrefetch.test.ts' 'ui/src/features/dashboard/bookings/lib/adminPageTransitionKey.test.ts' 'ui/src/features/dashboard/bookings/lib/adminSidebarNav.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingAiDocumentLinks.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingAiReviewProgress.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingAiValidations.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingAssetClearPatch.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingDetailActions.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingFinance.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingListDisplay.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingListNavigation.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingPastPipelineManila.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingStages.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingsListSort.test.ts' 'ui/src/features/dashboard/bookings/lib/bookingsSortOptions.test.ts' 'ui/src/features/dashboard/bookings/lib/buildingFormsTeamDefaults.test.ts' 'ui/src/features/dashboard/bookings/lib/documentRequirements.test.ts' 'ui/src/features/dashboard/bookings/lib/gafDefaults.test.ts' 'ui/src/features/dashboard/bookings/lib/gafPdfSignature.test.ts' 'ui/src/features/dashboard/bookings/lib/importCommitStatus.test.ts' 'ui/src/features/dashboard/bookings/lib/listView.test.ts' 'ui/src/features/dashboard/bookings/lib/normalizeBlockLevelPlaceholders.test.ts' 'ui/src/features/dashboard/bookings/lib/normalizeEmailCalloutPlaceholders.test.ts' 'ui/src/features/dashboard/bookings/lib/parkingFindPathFromBooking.test.ts' 'ui/src/features/dashboard/bookings/lib/parkingFindPathFromBooking.ts' 'ui/src/features/dashboard/bookings/lib/pendingDocApproval.test.ts' 'ui/src/features/dashboard/bookings/lib/petDefaults.test.ts' 'ui/src/features/dashboard/bookings/lib/propertyTemplatePlaceholders.test.ts' 'ui/src/features/dashboard/bookings/lib/propertyTemplateSections.test.ts' 'ui/src/features/dashboard/bookings/lib/storageUrls.test.ts' 'ui/src/features/dashboard/bookings/lib/telegramConnectionLabels.test.ts' 'ui/src/features/dashboard/bookings/lib/telegramDiscoverChats.test.ts' 'ui/src/features/dashboard/bookings/lib/telegramNotificationDefaults.test.ts' 'ui/src/features/dashboard/bookings/lib/telegramPlaceholderGroups.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): refresh host announcements surfaces
EOF
)"
git add -- 'ui/src/features/dashboard/bookings/lib/telegramPlaceholderGroups.ts' 'ui/src/features/dashboard/bookings/lib/telegramPreviewSamples.test.ts' 'ui/src/features/dashboard/bookings/lib/telegramTemplatePreview.test.ts' 'ui/src/features/dashboard/bookings/lib/templatePlaceholderCatalog.test.ts' 'ui/src/features/dashboard/bookings/lib/templatePlaceholderHighlight.test.ts' 'ui/src/features/dashboard/bookings/lib/templatePreviewReadonly.test.ts' 'ui/src/features/dashboard/bookings/lib/unitTypes.test.ts' 'ui/src/features/dashboard/bookings/lib/workflowActionButtonStyles.test.ts' 'ui/src/features/dashboard/bookings/lib/workflowAdvanceMode.test.ts' 'ui/src/features/dashboard/bookings/lib/workflowEmailTriggerAvailability.test.ts' 'ui/src/features/dashboard/bookings/lib/workflowPlanSkip.test.ts' 'ui/src/features/dashboard/bookings/lib/workflowStageDeck.test.ts' 'ui/src/features/dashboard/bookings/lib/workflowTransitionEffectsCopy.test.ts' 'ui/src/features/dashboard/bookings/lib/workflowTransitionEmailControls.test.ts' 'ui/src/features/dashboard/bookings/lib/normalizePropertyTemplateEditorContent.test.ts' 'ui/src/features/dashboard/bookings/lib/normalizePropertyTemplateEditorContent.ts' 'ui/src/features/dashboard/finance/components/FinanceTransactionModals.tsx' 'ui/src/features/dashboard/finance/components/OperatingLineItemForm.tsx' 'ui/src/features/dashboard/finance/components/RecurringSeriesModal.tsx' 'ui/src/features/dashboard/finance/lib/financeCategoryColors.test.ts' 'ui/src/features/dashboard/finance/lib/financeChartData.test.ts' 'ui/src/features/dashboard/finance/lib/financeFilterLabels.test.ts' 'ui/src/features/dashboard/finance/lib/financeLedger.test.ts' 'ui/src/features/dashboard/finance/lib/financePeriod.test.ts' 'ui/src/features/dashboard/finance/lib/financeReminderTemplate.test.ts' 'ui/src/features/dashboard/finance/lib/financeSummaryStats.test.ts' 'ui/src/features/dashboard/finance/lib/recurrence.test.ts' 'ui/src/features/dashboard/finance/components/OperatingLineItemFormPreview.tsx' 'ui/src/features/dashboard/finance/lib/operatingLineItemFormSteps.test.ts' 'ui/src/features/dashboard/finance/lib/operatingLineItemFormSteps.ts' 'ui/src/features/dashboard/help-support/components/NewTicketModal.tsx' 'ui/src/features/dashboard/help-support/hooks/useSupportTickets.ts' 'ui/src/features/dashboard/help-support/lib/helpContentDisplay.test.ts' 'ui/src/features/dashboard/help-support/lib/helpFaqModules.test.ts' 'ui/src/features/dashboard/help-support/lib/helpSupportPaths.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): update bookings workflow and property settings
EOF
)"
git add -- 'ui/src/features/dashboard/help-support/lib/supportTicketSchema.test.ts' 'ui/src/features/dashboard/help-support/lib/supportTicketStatus.test.ts' 'ui/src/features/dashboard/import/components/ImportRowFixSheet.tsx' 'ui/src/features/dashboard/import/components/ImportWizardModal.tsx' 'ui/src/features/dashboard/import/lib/importBatchWorkflow.test.ts' 'ui/src/features/dashboard/import/lib/importCsvTemplate.test.ts' 'ui/src/features/dashboard/import/lib/importEdgeResponse.test.ts' 'ui/src/features/dashboard/import/lib/importRowDraftValidation.test.ts' 'ui/src/features/dashboard/import/lib/importTargetFields.test.ts' 'ui/src/features/dashboard/import/lib/importUploadLimits.test.ts' 'ui/src/features/dashboard/inbox/components/InboxAiResponseDialog.tsx' 'ui/src/features/dashboard/inbox/components/InboxConversationView.tsx' 'ui/src/features/dashboard/inbox/components/InboxPinnedSnippetsPanel.tsx' 'ui/src/features/dashboard/inbox/components/InboxQuickReplyFormDialog.tsx' 'ui/src/features/dashboard/inbox/components/InboxThreadList.tsx' 'ui/src/features/dashboard/inbox/lib/inboxBookingShareRows.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxChatAttachment.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxCheckInPack.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxFormat.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxInsertContent.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxMatchBooking.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxMessageAttachments.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxNotifications.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxPinnedSnippets.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxQuickReplyLinks.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxQuickReplyMerge.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxShareBookingItems.test.ts' 'ui/src/features/dashboard/inbox/lib/inboxThreadPagination.test.ts' 'ui/src/features/dashboard/inbox/lib/metaInboxOAuthErrors.test.ts' 'ui/src/features/dashboard/inbox/lib/metaInboxSyncErrors.test.ts' 'ui/src/features/dashboard/inbox/lib/quickReplyGroups.test.ts' 'ui/src/features/dashboard/lib/storedMediaDisplay.test.ts' 'ui/src/features/dashboard/lib/useOpenDraftDirty.ts' 'ui/src/features/dashboard/maintenance/components/MaintenanceItemForm.tsx' 'ui/src/features/dashboard/maintenance/components/MaintenanceRemindersTab.tsx'
c

MSG="$(cat <<'EOF'
feat(ui): add property settings copy and voice fields
EOF
)"
git add -- 'ui/src/features/dashboard/maintenance/components/RecurringSeriesModal.tsx' 'ui/src/features/dashboard/maintenance/lib/maintenancePeriod.test.ts' 'ui/src/features/dashboard/maintenance/lib/maintenanceReminderTemplate.test.ts' 'ui/src/features/dashboard/maintenance/lib/maintenanceReminders.test.ts' 'ui/src/features/dashboard/maintenance/components/MaintenanceItemFormPreview.tsx' 'ui/src/features/dashboard/maintenance/lib/maintenanceItemFormSteps.test.ts' 'ui/src/features/dashboard/maintenance/lib/maintenanceItemFormSteps.ts' 'ui/src/features/dashboard/marketing/components/ai-studio/AiStudioComposer.tsx' 'ui/src/features/dashboard/marketing/components/ai-studio/AiStudioSection.tsx' 'ui/src/features/dashboard/marketing/components/calendar-builder/components/BookingsCalendarView.tsx' 'ui/src/features/dashboard/marketing/components/calendar-builder/components/CalendarBuilder.tsx' 'ui/src/features/dashboard/marketing/components/design-editor/PolotnoDesignStudio.tsx' 'ui/src/features/dashboard/marketing/components/design-editor/polotno/KamePolotnoEditor.tsx' 'ui/src/features/dashboard/marketing/components/shared/DesignAiGenerateVisuals.tsx' 'ui/src/features/dashboard/marketing/components/shared/MarketingAiGeneratePanel.tsx' 'ui/src/features/dashboard/marketing/components/shared/MarketingTemplateCard.tsx' 'ui/src/features/dashboard/marketing/components/shared/VideoAiGenerateVisuals.tsx' 'ui/src/features/dashboard/marketing/components/video-editor/VideoEditor.tsx' 'ui/src/features/dashboard/marketing/hooks/useMarketingAutoSave.ts' 'ui/src/features/dashboard/marketing/hooks/useMarketingPermissions.ts' 'ui/src/features/dashboard/marketing/lib/calendarAiGenerateOptions.test.ts' 'ui/src/features/dashboard/marketing/lib/calendarAiTokens.test.ts' 'ui/src/features/dashboard/marketing/lib/calendarAutosave.test.ts' 'ui/src/features/dashboard/marketing/lib/calendarBrandColors.test.ts' 'ui/src/features/dashboard/marketing/lib/calendarBrandTints.test.ts' 'ui/src/features/dashboard/marketing/lib/calendarCanvasFormats.test.ts' 'ui/src/features/dashboard/marketing/lib/calendarPropertyPhoto.test.ts' 'ui/src/features/dashboard/marketing/lib/collage/collageLayouts.test.ts' 'ui/src/features/dashboard/marketing/lib/collage/collageStoreOps.test.ts' 'ui/src/features/dashboard/marketing/lib/collage/collageTypes.test.ts' 'ui/src/features/dashboard/marketing/lib/designAiGenerateOptions.test.ts' 'ui/src/features/dashboard/marketing/lib/designAiTokens.test.ts' 'ui/src/features/dashboard/marketing/lib/designAutosave.test.ts' 'ui/src/features/dashboard/marketing/lib/designBrandColors.test.ts' 'ui/src/features/dashboard/marketing/lib/designCampaignTemplates.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): wire unsaved changes on booking settings
EOF
)"
git add -- 'ui/src/features/dashboard/marketing/lib/designCanvasService.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingAiPhotoPalette.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingBookedDates.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingCatalogHidden.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingContentFingerprint.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingDefaultBinding.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingFormats.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingGenerationOptions.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingGenerationPricing.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingGenerationPricing.ts' 'ui/src/features/dashboard/marketing/lib/marketingGenerationProgress.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingGuestReview.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingHtmlToImageOptions.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingIdle.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingReviewDesignSeed.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingSavedTemplates.test.ts' 'ui/src/features/dashboard/marketing/lib/marketingTemplateThumbnailCache.test.ts' 'ui/src/features/dashboard/marketing/lib/polotno/configurePolotnoOverlays.test.ts' 'ui/src/features/dashboard/marketing/lib/polotno/kamePolotnoShapes.test.ts' 'ui/src/features/dashboard/marketing/lib/polotno/orgLogoCircle.test.ts' 'ui/src/features/dashboard/marketing/lib/polotno/polotnoAiCampaignDocuments.test.ts' 'ui/src/features/dashboard/marketing/lib/polotno/polotnoCampaignDocuments.test.ts' 'ui/src/features/dashboard/marketing/lib/polotno/polotnoStore.test.ts' 'ui/src/features/dashboard/marketing/lib/polotno/polotnoWorkspaceTheme.test.ts' 'ui/src/features/dashboard/marketing/lib/polotno/propertyMedia.test.ts' 'ui/src/features/dashboard/marketing/lib/polotno/roundedOutlineSvg.test.ts' 'ui/src/features/dashboard/marketing/lib/propertyBindingMedia.test.ts' 'ui/src/features/dashboard/marketing/lib/renderMarketingVideoThumbnail.test.ts' 'ui/src/features/dashboard/marketing/lib/video/applyGuestReviewToVideoProject.test.ts' 'ui/src/features/dashboard/marketing/lib/video/importVideoMusic.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoAiProjectBuilder.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoCategories.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoFormatDimensions.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoLayerSizing.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoLayerTypography.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): extend finance module and reminders
EOF
)"
git add -- 'ui/src/features/dashboard/marketing/lib/video/videoMotionProfiles.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoMusicPresets.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoProjectDefaults.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoProjectTypes.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoProjectUtils.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoSceneElements.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoSceneKindChange.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoSceneLayers.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoSceneTexts.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoStoryboardRecipes.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoTemplateLayouts.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoTemplateTypography.test.ts' 'ui/src/features/dashboard/marketing/lib/video/videoTextSlots.test.ts' 'ui/src/features/dashboard/marketing/lib/videoAiGenerateOptions.test.ts' 'ui/src/features/dashboard/marketing/lib/videoAiTokens.test.ts' 'ui/src/features/dashboard/marketing/lib/videoCampaignTemplates.test.ts' 'ui/src/features/dashboard/marketing/lib/videoThumbnailCapture.test.ts' 'ui/src/features/dashboard/notifications/lib/notificationsCollapse.test.ts' 'ui/src/features/dashboard/notifications/lib/notificationsDisplay.test.ts' 'ui/src/features/dashboard/notifications/lib/notificationsPaths.test.ts' 'ui/src/features/dashboard/notifications/lib/notificationsScope.test.ts' 'ui/src/features/dashboard/org/components/AddEntityDialog.tsx' 'ui/src/features/dashboard/org/components/RequireOrgNotHardRejected.tsx' 'ui/src/features/dashboard/org/components/listing-authorization/ListingContractConsiderationForm.tsx' 'ui/src/features/dashboard/org/components/listing-authorization/ListingContractRenewalModal.tsx' 'ui/src/features/dashboard/org/components/listing-authorization/ListingVerificationModal.tsx' 'ui/src/features/dashboard/org/components/org-parkings/OrgParkingsSummaryCards.tsx' 'ui/src/features/dashboard/org/components/org-parkings/OrgParkingsToolbar.tsx' 'ui/src/features/dashboard/org/components/org-properties/CopyPropertySettingsDialog.tsx' 'ui/src/features/dashboard/org/components/org-properties/CopyPropertySettingsHistory.tsx' 'ui/src/features/dashboard/org/components/org-properties/OrgPropertiesSummaryCards.tsx' 'ui/src/features/dashboard/org/components/org-properties/OrgPropertiesToolbar.tsx' 'ui/src/features/dashboard/org/components/org-settings/OrgAiDashboardAssistantSection.tsx' 'ui/src/features/dashboard/org/components/org-settings/OrgAiPlatformSection.tsx' 'ui/src/features/dashboard/org/components/org-settings/OrgProfileSettingsSections.tsx'
c

MSG="$(cat <<'EOF'
feat(ui): add help support and import wizard guards
EOF
)"
git add -- 'ui/src/features/dashboard/org/components/org-settings/OrgSuperhostProgressSection.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyAiPlatformSection.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyCancellationPolicySection.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyExternalReviewsBlock.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyLocationSettingsBlock.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyOperationalSettingsSections.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyProfileSettingsSections.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertySocialsBrandingSection.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyVoiceReceptionistSection.tsx' 'ui/src/features/dashboard/org/components/property-settings/PublicPagesCrossLink.tsx' 'ui/src/features/dashboard/org/components/property-settings/SensitiveSettingsOtpDialog.tsx' 'ui/src/features/dashboard/org/components/verification/GetVerifiedModal.tsx' 'ui/src/features/dashboard/org/hooks/useAiPlatformSettings.ts' 'ui/src/features/dashboard/org/lib/adminApiScope.test.ts' 'ui/src/features/dashboard/org/lib/adminAssetScope.test.ts' 'ui/src/features/dashboard/org/lib/adminParkingScope.test.ts' 'ui/src/features/dashboard/org/lib/aiQuotaToast.test.ts' 'ui/src/features/dashboard/org/lib/contractLifecycle.test.ts' 'ui/src/features/dashboard/org/lib/copyPropertySettingsGroups.ts' 'ui/src/features/dashboard/org/lib/formatParkingLocation.test.ts' 'ui/src/features/dashboard/org/lib/listingAuthorization.test.ts' 'ui/src/features/dashboard/org/lib/listingContractRenewalCandidates.test.ts' 'ui/src/features/dashboard/org/lib/listingContractRenewalCopy.test.ts' 'ui/src/features/dashboard/org/lib/listingContractRenewalDismiss.test.ts' 'ui/src/features/dashboard/org/lib/listingContractRenewalDismissScope.test.ts' 'ui/src/features/dashboard/org/lib/listingVerificationCopy.test.ts' 'ui/src/features/dashboard/org/lib/listingVerificationTiers.test.ts' 'ui/src/features/dashboard/org/lib/orgAccessKind.test.ts' 'ui/src/features/dashboard/org/lib/orgDevelopments.test.ts' 'ui/src/features/dashboard/org/lib/orgLanding.test.ts' 'ui/src/features/dashboard/org/lib/orgParkingCardModel.test.ts' 'ui/src/features/dashboard/org/lib/orgParkingDisplay.test.ts' 'ui/src/features/dashboard/org/lib/orgParkingsFilters.test.ts' 'ui/src/features/dashboard/org/lib/orgParkingsFilters.ts' 'ui/src/features/dashboard/org/lib/orgPropertiesFilters.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): update inbox quick replies and settings
EOF
)"
git add -- 'ui/src/features/dashboard/org/lib/orgPropertiesFilters.ts' 'ui/src/features/dashboard/org/lib/orgPropertyCardModel.test.ts' 'ui/src/features/dashboard/org/lib/orgPropertyDisplay.test.ts' 'ui/src/features/dashboard/org/lib/orgSettingsCompletion.test.ts' 'ui/src/features/dashboard/org/lib/orgSettingsFieldError.test.ts' 'ui/src/features/dashboard/org/lib/orgSettingsForm.test.ts' 'ui/src/features/dashboard/org/lib/orgSettingsIssuesStore.test.ts' 'ui/src/features/dashboard/org/lib/orgSettingsSave.test.ts' 'ui/src/features/dashboard/org/lib/orgSettingsValidation.test.ts' 'ui/src/features/dashboard/org/lib/orgSuperhost.test.ts' 'ui/src/features/dashboard/org/lib/orgVerification.test.ts' 'ui/src/features/dashboard/org/lib/orgVerificationTiers.test.ts' 'ui/src/features/dashboard/org/lib/parkingResidences.test.ts' 'ui/src/features/dashboard/org/lib/parkingResidences.ts' 'ui/src/features/dashboard/org/lib/parkingSlotConflict.test.ts' 'ui/src/features/dashboard/org/lib/parkingSlotDisplay.test.ts' 'ui/src/features/dashboard/org/lib/paymentMethods.test.ts' 'ui/src/features/dashboard/org/lib/paymentProviders.test.ts' 'ui/src/features/dashboard/org/lib/postSignInRouting.test.ts' 'ui/src/features/dashboard/org/lib/propertyCancellationPolicy.test.ts' 'ui/src/features/dashboard/org/lib/propertyDisplay.test.ts' 'ui/src/features/dashboard/org/lib/propertyDocumentRequirements.test.ts' 'ui/src/features/dashboard/org/lib/propertyEmailAutomation.test.ts' 'ui/src/features/dashboard/org/lib/propertyEmailAutomationDefaults.test.ts' 'ui/src/features/dashboard/org/lib/propertyExternalReviews.test.ts' 'ui/src/features/dashboard/org/lib/propertyHouseRulesConstants.test.ts' 'ui/src/features/dashboard/org/lib/propertyLocation.test.ts' 'ui/src/features/dashboard/org/lib/propertyMedia.test.ts' 'ui/src/features/dashboard/org/lib/propertyResidenceDefaults.test.ts' 'ui/src/features/dashboard/org/lib/propertyResidences.test.ts' 'ui/src/features/dashboard/org/lib/propertySettingsCompletion.test.ts' 'ui/src/features/dashboard/org/lib/propertySettingsCompletion.ts' 'ui/src/features/dashboard/org/lib/propertySettingsConstants.test.ts' 'ui/src/features/dashboard/org/lib/propertySettingsFieldError.test.ts' 'ui/src/features/dashboard/org/lib/propertySettingsForm.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): extend maintenance tabs and skeletons
EOF
)"
git add -- 'ui/src/features/dashboard/org/lib/propertySettingsIssuesStore.test.ts' 'ui/src/features/dashboard/org/lib/propertySettingsSave.test.ts' 'ui/src/features/dashboard/org/lib/propertySocialLinks.test.ts' 'ui/src/features/dashboard/org/lib/propertyTowerUnit.test.ts' 'ui/src/features/dashboard/org/lib/propertyTowerUnitConflict.test.ts' 'ui/src/features/dashboard/org/lib/propertyVoucherSettings.test.ts' 'ui/src/features/dashboard/org/lib/settingsFieldLabel.test.ts' 'ui/src/features/dashboard/org/lib/socialPlatformTypes.test.ts' 'ui/src/features/dashboard/org/lib/tenantPaths.test.ts' 'ui/src/features/dashboard/org/lib/verificationCopy.test.ts' 'ui/src/features/dashboard/org/lib/voiceReceptionistVoicePreview.test.ts' 'ui/src/features/dashboard/org/lib/voucherRevealStyle.test.ts' 'ui/src/features/dashboard/org/pages/OnboardingPage.tsx' 'ui/src/features/dashboard/org/pages/OrgParkingsPage.tsx' 'ui/src/features/dashboard/org/pages/OrgPropertiesPage.tsx' 'ui/src/features/dashboard/org/pages/OrgSettingsPage.tsx' 'ui/src/features/dashboard/org/components/OrgListingToolbar.tsx' 'ui/src/features/dashboard/org/components/OrgListingViewToggle.tsx' 'ui/src/features/dashboard/org/components/TenantSlugRemapRedirect.tsx' 'ui/src/features/dashboard/org/components/org-parkings/OrgParkingsTable.tsx' 'ui/src/features/dashboard/org/components/org-properties/OrgPropertiesTable.tsx' 'ui/src/features/dashboard/org/components/org-settings/OrgAiSettingsSection.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyAiSettingsSection.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyVoiceReceptionistFields.tsx' 'ui/src/features/dashboard/org/components/settings/AiSettingsChrome.tsx' 'ui/src/features/dashboard/org/hooks/useOrgListingPagination.ts' 'ui/src/features/dashboard/org/hooks/useOrgListingViewMode.ts' 'ui/src/features/dashboard/org/lib/aiSettingsLabels.ts' 'ui/src/features/dashboard/org/lib/buildingFormsManage.test.ts' 'ui/src/features/dashboard/org/lib/buildingFormsManage.ts' 'ui/src/features/dashboard/org/lib/orgListingPagination.test.ts' 'ui/src/features/dashboard/org/lib/orgListingPagination.ts' 'ui/src/features/dashboard/org/lib/orgListingViewMode.test.ts' 'ui/src/features/dashboard/org/lib/orgListingViewMode.ts' 'ui/src/features/dashboard/org/lib/orgSuperhostDisplay.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): polish marketing ai studio components
EOF
)"
git add -- 'ui/src/features/dashboard/org/lib/orgSuperhostDisplay.ts' 'ui/src/features/dashboard/org/lib/tenantSlugRemap.test.ts' 'ui/src/features/dashboard/org/lib/tenantSlugRemap.ts' 'ui/src/features/dashboard/page-editor/components/PageEditorLeaveConfirmDialog.tsx' 'ui/src/features/dashboard/page-editor/components/property-landing/PropertyLandingEditorPanel.tsx' 'ui/src/features/dashboard/page-editor/components/property-showcase/PropertyShowcasePageEditor.tsx' 'ui/src/features/dashboard/page-editor/components/stay-guide/StayGuidePageEditor.tsx' 'ui/src/features/dashboard/page-editor/lib/pageEditorPublicLinks.test.ts' 'ui/src/features/dashboard/page-editor/lib/resolveShowcaseTemplatePickerPalette.test.ts' 'ui/src/features/dashboard/page-editor/lib/showcaseSectionEditorCopy.test.ts' 'ui/src/features/dashboard/page-editor/lib/showcaseSectionEditorFields.test.ts' 'ui/src/features/dashboard/page-editor/lib/showcaseTemplateThumbData.test.ts' 'ui/src/features/dashboard/page-editor/lib/stayGuideTemplateThumbData.test.ts' 'ui/src/features/dashboard/page-editor/pages/PageEditorPage.tsx' 'ui/src/features/dashboard/parking/components/AdminParkingNewBookingModal.tsx' 'ui/src/features/dashboard/parking/components/ParkingNotificationTemplatesCard.tsx' 'ui/src/features/dashboard/parking/components/ParkingSettingsCard.tsx' 'ui/src/features/dashboard/parking/components/TelegramParkingSettingsCard.tsx' 'ui/src/features/dashboard/parking/lib/parkingDashboardStats.test.ts' 'ui/src/features/dashboard/parking/lib/parkingDimensionDefaults.test.ts' 'ui/src/features/dashboard/parking/lib/parkingEmailAutomation.test.ts' 'ui/src/features/dashboard/parking/lib/parkingFeaturesConstants.test.ts' 'ui/src/features/dashboard/parking/lib/parkingPricingCompute.test.ts' 'ui/src/features/dashboard/parking/lib/parkingPricingDefaults.test.ts' 'ui/src/features/dashboard/parking/lib/parkingPricingSave.test.ts' 'ui/src/features/dashboard/parking/lib/parkingSettingsCompletion.test.ts' 'ui/src/features/dashboard/parking/lib/parkingSettingsFieldError.test.ts' 'ui/src/features/dashboard/parking/lib/parkingSettingsForm.test.ts' 'ui/src/features/dashboard/parking/lib/parkingSettingsIssuesStore.test.ts' 'ui/src/features/dashboard/parking/lib/parkingSettingsSavePlan.test.ts' 'ui/src/features/dashboard/parking/lib/parkingWorkflow.test.ts' 'ui/src/features/dashboard/parking/pages/ParkingPricingPage.tsx' 'ui/src/features/dashboard/plans/components/OrgPlanTransactions.tsx' 'ui/src/features/dashboard/plans/components/PlanBillingPanel.tsx' 'ui/src/features/dashboard/plans/components/PlanCheckoutConfirmationBanner.tsx'
c

MSG="$(cat <<'EOF'
feat(ui): update marketing generation and templates
EOF
)"
git add -- 'ui/src/features/dashboard/plans/components/PlanFaqSection.tsx' 'ui/src/features/dashboard/plans/components/PlanFeatureMatrix.tsx' 'ui/src/features/dashboard/plans/components/PlanTierRail.tsx' 'ui/src/features/dashboard/plans/hooks/useOrgPlanCheckoutConfirmation.ts' 'ui/src/features/dashboard/plans/lib/featureGateCopy.test.ts' 'ui/src/features/dashboard/plans/lib/openOrgPlanCheckout.test.ts' 'ui/src/features/dashboard/plans/lib/orgEntitlements.test.ts' 'ui/src/features/dashboard/plans/lib/orgPlanCheckoutParams.test.ts' 'ui/src/features/dashboard/plans/lib/orgPlanCheckoutSession.test.ts' 'ui/src/features/dashboard/plans/lib/planPresentation.test.ts' 'ui/src/features/dashboard/plans/lib/planPresentation.ts' 'ui/src/features/dashboard/plans/lib/planPricing.test.ts' 'ui/src/features/dashboard/plans/lib/planProration.test.ts' 'ui/src/features/dashboard/plans/lib/planStubPayToast.test.ts' 'ui/src/features/dashboard/plans/lib/planTierIcons.test.ts' 'ui/src/features/dashboard/plans/lib/upgradeModalBridge.test.ts' 'ui/src/features/dashboard/plans/pages/OrgPlansPage.tsx' 'ui/src/features/dashboard/plans/components/OrgPlanSidebarEntry.tsx' 'ui/src/features/dashboard/plans/lib/orgPlanTransactionFormat.test.ts' 'ui/src/features/dashboard/plans/lib/orgPlanTransactionFormat.ts' 'ui/src/features/dashboard/plans/lib/planDisplayCopy.test.ts' 'ui/src/features/dashboard/plans/lib/planFeaturePermissions.test.ts' 'ui/src/features/dashboard/plans/lib/planFeaturePermissions.ts' 'ui/src/features/dashboard/plans/lib/planFeatureRows.test.ts' 'ui/src/features/dashboard/plans/lib/planFeaturesParity.test.ts' 'ui/src/features/dashboard/plans/lib/planGateCoverage.test.ts' 'ui/src/features/dashboard/plans/lib/planTierCardGains.test.ts' 'ui/src/features/dashboard/plans/lib/planTierExpectations.test.ts' 'ui/src/features/dashboard/plans/lib/planTierExpectations.ts' 'ui/src/features/dashboard/plans/lib/planTierGolden.test.ts' 'ui/src/features/dashboard/plans/lib/planTierGolden.ts' 'ui/src/features/dashboard/plans/lib/planTierPricing.test.ts' 'ui/src/features/dashboard/plans/lib/planUpgradeRouting.test.ts' 'ui/src/features/dashboard/pricing/components/SmartPricingDialog.tsx' 'ui/src/features/dashboard/pricing/lib/phHolidayRules.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): extend org hub analytics and settings
EOF
)"
git add -- 'ui/src/features/dashboard/pricing/lib/pricingCalendarUtils.test.ts' 'ui/src/features/dashboard/pricing/lib/pricingCompute.test.ts' 'ui/src/features/dashboard/pricing/lib/pricingDefaults.test.ts' 'ui/src/features/dashboard/pricing/lib/pricingSave.test.ts' 'ui/src/features/dashboard/pricing/lib/smartPricingPreviewExplain.test.ts' 'ui/src/features/dashboard/pricing/pages/PropertyPricingPage.tsx' 'ui/src/features/dashboard/property/lib/dashboardFinanceTransactions.test.ts' 'ui/src/features/dashboard/property/lib/dashboardPeriod.test.ts' 'ui/src/features/dashboard/property/lib/propertyGuestPublicPages.test.ts' 'ui/src/features/dashboard/property/lib/resolvePropertyDashboardHref.test.ts' 'ui/src/features/dashboard/setup-guide/components/SetupGuideOverlay.tsx' 'ui/src/features/dashboard/setup-guide/components/SetupGuidePricingEmbed.tsx' 'ui/src/features/dashboard/setup-guide/components/SetupGuideSaveContext.tsx' 'ui/src/features/dashboard/setup-guide/components/SetupGuideStepBody.tsx' 'ui/src/features/dashboard/setup-guide/components/SetupGuideStepSkeleton.tsx' 'ui/src/features/dashboard/setup-guide/components/SetupGuideTeamEmbed.tsx' 'ui/src/features/dashboard/setup-guide/lib/setupGuideIssuesStore.test.ts' 'ui/src/features/dashboard/setup-guide/lib/setupGuideState.test.ts' 'ui/src/features/dashboard/super-admin/components/AiDashboardAssistantKillSwitchCard.tsx' 'ui/src/features/dashboard/super-admin/components/AiPlatformKillSwitchCard.tsx' 'ui/src/features/dashboard/super-admin/components/HostVerificationRewardCard.tsx' 'ui/src/features/dashboard/super-admin/components/SuperAdminGenerationOverridesCard.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-announcements/SuperAdminAnnouncementDialog.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-announcements/SuperAdminAnnouncementTable.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-development-settings/DevelopmentSettingsCard.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-developments/AddDevelopmentDialog.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-overview/SuperAdminOverviewKpis.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-pricing/EditPricingPlanDialog.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-support/SuperAdminFaqEditorDialog.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-support/SuperAdminPlaybookArticleEditorDialog.tsx' 'ui/src/features/dashboard/super-admin/hooks/useSuperAdminAiUsage.ts' 'ui/src/features/dashboard/super-admin/lib/approvalReviewTier.test.ts' 'ui/src/features/dashboard/super-admin/lib/developmentGuestInfo.test.ts' 'ui/src/features/dashboard/super-admin/lib/developmentLocation.test.ts' 'ui/src/features/dashboard/super-admin/lib/developmentMedia.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): add org ai settings and superhost sections
EOF
)"
git add -- 'ui/src/features/dashboard/super-admin/lib/developmentParking.test.ts' 'ui/src/features/dashboard/super-admin/lib/developmentSettingsConstants.test.ts' 'ui/src/features/dashboard/super-admin/lib/developmentSettingsForm.test.ts' 'ui/src/features/dashboard/super-admin/lib/hostPropertyAdapter.test.ts' 'ui/src/features/dashboard/super-admin/lib/listingApprovalReviewTier.test.ts' 'ui/src/features/dashboard/super-admin/lib/listingRequestChangesMessage.test.ts' 'ui/src/features/dashboard/super-admin/lib/platformPropertyAdapter.test.ts' 'ui/src/features/dashboard/super-admin/lib/pricingPlanDisplay.test.ts' 'ui/src/features/dashboard/super-admin/lib/rejectReasonOptions.test.ts' 'ui/src/features/dashboard/super-admin/lib/requestChangesMessage.test.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminAnnouncementFilters.test.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminApprovalsFilters.test.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminDevelopmentsFilters.test.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminHostsFilters.test.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminPaths.test.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminPaths.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminPlatformNav.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminPlatformPropertiesFilters.test.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminPricingFilters.test.ts' 'ui/src/features/dashboard/super-admin/lib/superAdminSupportFilters.test.ts' 'ui/src/features/dashboard/super-admin/pages/SuperAdminAiUsagePage.tsx' 'ui/src/features/dashboard/super-admin/pages/SuperAdminOrgAiSection.tsx' 'ui/src/features/dashboard/super-admin/pages/SuperAdminOrgSettingsSection.tsx' 'ui/src/features/dashboard/super-admin/pages/SuperAdminParkingPayoutsPage.tsx' 'ui/src/features/dashboard/super-admin/pages/SuperAdminPaymentSettingsPage.tsx' 'ui/src/features/dashboard/super-admin/pages/SuperAdminPlatformSettingsPage.tsx' 'ui/src/features/dashboard/super-admin/pages/SuperAdminPricingPlansPage.tsx' 'ui/src/features/dashboard/super-admin/pages/SuperAdminRateLimitsPage.tsx' 'ui/src/features/dashboard/super-admin/pages/SuperAdminSettingsPage.tsx' 'ui/src/features/dashboard/super-admin/routes/index.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiAssignDialog.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiLimitFields.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiLimitsTab.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiOrgLimitsSheet.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiOverrideDialog.tsx'
c

MSG="$(cat <<'EOF'
feat(ui): wire unsaved changes on org settings
EOF
)"
git add -- 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiProfileDialog.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiProfilesTab.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiProvenanceBadge.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiResolvedLimits.tsx' 'ui/src/features/dashboard/super-admin/components/super-admin-ai/AiUsageTab.tsx' 'ui/src/features/dashboard/super-admin/hooks/useSuperAdminAiLimits.ts' 'ui/src/features/dashboard/super-admin/lib/aiLimits.test.ts' 'ui/src/features/dashboard/super-admin/lib/aiLimits.ts' 'ui/src/features/dashboard/super-admin/pages/SuperAdminAiPage.tsx' 'ui/src/features/dashboard/team/components/ApplyTemplatePicker.tsx' 'ui/src/features/dashboard/team/components/CustomRoleFormDialog.tsx' 'ui/src/features/dashboard/team/components/CustomRolesSection.tsx' 'ui/src/features/dashboard/team/components/EditMemberContactDialog.tsx' 'ui/src/features/dashboard/team/components/InviteMemberDialog.tsx' 'ui/src/features/dashboard/team/components/OrgInviteMemberDialog.tsx' 'ui/src/features/dashboard/team/components/OrgManageMemberDialog.tsx' 'ui/src/features/dashboard/team/components/OrgTeamMembersTab.tsx' 'ui/src/features/dashboard/team/components/PermissionsTreeView.tsx' 'ui/src/features/dashboard/team/components/TeamMemberStatusBadge.tsx' 'ui/src/features/dashboard/team/components/TeamMembersTab.tsx' 'ui/src/features/dashboard/team/lib/accessPermissionExpansion.test.ts' 'ui/src/features/dashboard/team/lib/bookingsPermissionExpansion.test.ts' 'ui/src/features/dashboard/team/lib/formatTeamInvitationDate.test.ts' 'ui/src/features/dashboard/team/lib/legacyPermissionExpansion.test.ts' 'ui/src/features/dashboard/team/lib/listingAssignmentRoles.test.ts' 'ui/src/features/dashboard/team/lib/opsPermissionExpansion.test.ts' 'ui/src/features/dashboard/team/lib/orgLegacyPermissionExpansion.test.ts' 'ui/src/features/dashboard/team/lib/orgMemberRoleDisplay.test.ts' 'ui/src/features/dashboard/team/lib/orgPermissionCatalog.ts' 'ui/src/features/dashboard/team/lib/orgPermissions.test.ts' 'ui/src/features/dashboard/team/lib/orgPermissions.ts' 'ui/src/features/dashboard/team/lib/orgRoleListingScope.test.ts' 'ui/src/features/dashboard/team/lib/orgTeamConstants.test.ts' 'ui/src/features/dashboard/team/lib/orgTeamConstants.ts' 'ui/src/features/dashboard/team/lib/orgTeamRoles.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): update parking settings pricing and team
EOF
)"
git add -- 'ui/src/features/dashboard/team/lib/orgTeamTemplates.test.ts' 'ui/src/features/dashboard/team/lib/parkingPermissions.test.ts' 'ui/src/features/dashboard/team/lib/parkingPermissions.ts' 'ui/src/features/dashboard/team/lib/parkingTeamConstants.test.ts' 'ui/src/features/dashboard/team/lib/parkingTeamConstants.ts' 'ui/src/features/dashboard/team/lib/permissionTreeState.test.ts' 'ui/src/features/dashboard/team/lib/planLimitedTeamCopy.test.ts' 'ui/src/features/dashboard/team/lib/propertyPermissionCatalog.test.ts' 'ui/src/features/dashboard/team/lib/propertyPermissionCatalog.ts' 'ui/src/features/dashboard/team/lib/propertyPermissions.ts' 'ui/src/features/dashboard/team/lib/propertyTeamConstants.test.ts' 'ui/src/features/dashboard/team/lib/propertyTeamConstants.ts' 'ui/src/features/dashboard/team/lib/propertyTeamRoles.test.ts' 'ui/src/features/dashboard/team/lib/propertyTeamTemplates.test.ts' 'ui/src/features/dashboard/team/lib/roleSelectUtils.test.ts' 'ui/src/features/dashboard/team/lib/settingsPermissionExpansion.test.ts' 'ui/src/features/dashboard/team/lib/sortTeamMembersByCurrentUser.test.ts' 'ui/src/features/dashboard/team/lib/teamInviteContact.test.ts' 'ui/src/features/dashboard/team/lib/teamInviteEmail.test.ts' 'ui/src/features/dashboard/team/lib/teamMemberAccess.test.ts' 'ui/src/features/dashboard/team/lib/teamMemberContact.test.ts' 'ui/src/features/dashboard/team/lib/teamRoleHelpers.test.ts' 'ui/src/features/dashboard/team/lib/teamRoleToast.test.ts' 'ui/src/features/dashboard/team/lib/teamScopeConfig.test.ts' 'ui/src/features/dashboard/team/lib/teamScopeConfig.ts' 'ui/src/features/dashboard/team/pages/OrgTeamPage.tsx' 'ui/src/features/dashboard/team/pages/ParkingTeamPage.tsx' 'ui/src/features/dashboard/team/pages/PropertyTeamPage.tsx' 'ui/src/features/dashboard/team/components/CustomRoleFormPreview.tsx' 'ui/src/features/dashboard/team/lib/customRoleFormSteps.test.ts' 'ui/src/features/dashboard/team/lib/customRoleFormSteps.ts' 'ui/src/features/dashboard/team/lib/seededTemplatesDrift.test.ts' 'docs/architecture/ai-dashboard-assistant.md' 'docs/architecture/ai-platform.md' 'docs/architecture/data-model.md'
c

MSG="$(cat <<'EOF'
docs(docs): extend plans tier gates and checkout e2e
EOF
)"
git add -- 'docs/architecture/edge-functions.md' 'docs/architecture/integrations.md' 'docs/architecture/overview.md' 'docs/architecture/plans-feature-matrix.md' 'docs/architecture/smart-pricing.md' 'docs/architecture/validation-and-env.md' 'docs/architecture/unsaved-changes.md' 'docs/archive/operations/migration-runbook.md' 'docs/guides/routes/README.md' 'docs/guides/routes/account/profile.md' 'docs/guides/routes/admin/announcements.md' 'docs/guides/routes/admin/development-detail.md' 'docs/guides/routes/admin/developments.md' 'docs/guides/routes/admin/orgs.md' 'docs/guides/routes/admin/overview.md' 'docs/guides/routes/admin/parking-payouts.md' 'docs/guides/routes/admin/payment-settings.md' 'docs/guides/routes/admin/platform-tools.md' 'docs/guides/routes/admin/playbook.md' 'docs/guides/routes/admin/pricing-plans.md' 'docs/guides/routes/admin/settings.md' 'docs/guides/routes/admin/support.md' 'docs/guides/routes/form.md' 'docs/guides/routes/index-landing.md' 'docs/guides/routes/legal.md' 'docs/guides/routes/onboarding.md' 'docs/guides/routes/org/activity.md' 'docs/guides/routes/org/analytics.md' 'docs/guides/routes/org/announcements.md' 'docs/guides/routes/org/help-support.md' 'docs/guides/routes/org/inbox.md' 'docs/guides/routes/org/parking/activity.md' 'docs/guides/routes/org/parking/announcements.md' 'docs/guides/routes/org/parking/finance.md' 'docs/guides/routes/org/parking/help-support.md'
c

MSG="$(cat <<'EOF'
docs(docs): add plan catalog checks and presentation
EOF
)"
git add -- 'docs/guides/routes/org/parking/inbox.md' 'docs/guides/routes/org/parking/pricing.md' 'docs/guides/routes/org/parking/settings.md' 'docs/guides/routes/org/parking/team.md' 'docs/guides/routes/org/parkings.md' 'docs/guides/routes/org/plans.md' 'docs/guides/routes/org/properties.md' 'docs/guides/routes/org/property/activity.md' 'docs/guides/routes/org/property/analytics.md' 'docs/guides/routes/org/property/announcements.md' 'docs/guides/routes/org/property/bookings-detail.md' 'docs/guides/routes/org/property/finance.md' 'docs/guides/routes/org/property/help-support.md' 'docs/guides/routes/org/property/inbox.md' 'docs/guides/routes/org/property/maintenance.md' 'docs/guides/routes/org/property/marketing.md' 'docs/guides/routes/org/property/pricing.md' 'docs/guides/routes/org/property/public-pages.md' 'docs/guides/routes/org/property/settings.md' 'docs/guides/routes/org/property/team.md' 'docs/guides/routes/org/property/templates.md' 'docs/guides/routes/org/settings.md' 'docs/guides/routes/org/setup-guide.md' 'docs/guides/routes/org/team.md' 'docs/guides/routes/sd-form.md' 'docs/guides/routes/admin/ai.md' 'docs/PROJECT.md' 'docs/README.md' 'docs/workflow/done/README.md' 'docs/workflow/done/production-readiness-hardening.md' 'docs/workflow/for-testing/README.md' 'docs/workflow/for-testing/host-analytics-module.md' 'docs/workflow/for-testing/property-settings-copy-to-properties.md' 'docs/workflow/for-testing/superhost-program.md' 'docs/workflow/in-progress/README.md'
c

MSG="$(cat <<'EOF'
docs(docs): update property dashboard modules
EOF
)"
git add -- 'docs/workflow/intake/_to-plan.md' 'docs/workflow/intake/_to-prompt.md' 'docs/workflow/planned/README.md' 'docs/workflow/planned/ai-chat-mode.md' 'docs/workflow/qa/property-dashboard/12-public-pages.md' 'docs/workflow/done/ai-settings-super-admin-ownership.md' 'docs/workflow/done/plan-tier-test-suite.md' 'docs/workflow/done/team-permissions-plan-coverage-audit.md' 'docs/workflow/for-testing/activity-modal-ui-polish.md' 'docs/workflow/for-testing/org-portfolio-analytics-redesign.md' 'docs/workflow/planned/unified-ai-settings-card.md' 'ui/src/features/guest/account/components/GuestProfileForm.tsx' 'ui/src/features/guest/account/components/GuestProfileModal.tsx' 'ui/src/features/guest/account/lib/guestAccountIdentity.test.ts' 'ui/src/features/guest/account/lib/guestAccountNav.test.ts' 'ui/src/features/guest/account/lib/guestAccountPaths.test.ts' 'ui/src/features/guest/account/lib/voucherDiscount.test.ts' 'ui/src/features/guest/auth/lib/authRedirect.test.ts' 'ui/src/features/guest/auth/lib/guestAuthPaths.test.ts' 'ui/src/features/guest/auth/lib/guestAuthResume.test.ts' 'ui/src/features/guest/auth/lib/hostAuthPaths.test.ts' 'ui/src/features/guest/calendar/lib/guestCalendarAvailability.test.ts' 'ui/src/features/guest/chat/components/GuestChatHeaderBar.tsx' 'ui/src/features/guest/chat/lib/guestChatInsertItems.test.ts' 'ui/src/features/guest/chat/lib/guestChatResourceHubItems.test.ts' 'ui/src/features/guest/chat/lib/guestChatSuggestions.test.ts' 'ui/src/features/guest/chat/lib/voiceAudioCodec.test.ts' 'ui/src/features/guest/form/components/GuestForm.tsx' 'ui/src/features/guest/form/lib/bookingFormatter.test.ts' 'ui/src/features/guest/form/lib/bookingSourceFromSearchParams.test.ts' 'ui/src/features/guest/form/lib/findUsOptions.test.ts' 'ui/src/features/guest/form/lib/guestCounts.test.ts' 'ui/src/features/guest/form/lib/guestFormBranding.test.ts' 'ui/src/features/guest/form/lib/guestFormPayment.test.ts' 'ui/src/features/guest/form/lib/guestFormPropertyDefaults.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): extend super-admin ai console and limits
EOF
)"
git add -- 'ui/src/features/guest/form/lib/guestPropertyScope.test.ts' 'ui/src/features/guest/lib/guestEmbedPreview.test.ts' 'ui/src/features/guest/marketing/contact/lib/publicContactParams.test.ts' 'ui/src/features/guest/marketing/developments/lib/developmentsQuery.test.ts' 'ui/src/features/guest/marketing/developments/lib/groupDevelopmentsByLocation.test.ts' 'ui/src/features/guest/marketing/developments/lib/parkingSlotDisplay.test.ts' 'ui/src/features/guest/marketing/developments/lib/parkingSlotFilters.test.ts' 'ui/src/features/guest/marketing/developments/lib/parkingSlotMedia.test.ts' 'ui/src/features/guest/marketing/developments/lib/resolvePublicDevelopment.test.ts' 'ui/src/features/guest/marketing/for-hosts/components/film/scenes/SceneAct1.tsx' 'ui/src/features/guest/marketing/for-hosts/components/film/scenes/SceneAct2.tsx' 'ui/src/features/guest/marketing/for-hosts/components/film/scenes/SceneAct3.tsx' 'ui/src/features/guest/marketing/for-hosts/lib/scrollToSection.test.ts' 'ui/src/features/guest/marketing/forms/lib/parkingFormCopy.test.ts' 'ui/src/features/guest/marketing/guest-landing/lib/heroSearchCalendarClassNames.test.ts' 'ui/src/features/guest/marketing/hosts/lib/hostListingGrid.test.ts' 'ui/src/features/guest/marketing/pages/ParkingFormPage.tsx' 'ui/src/features/guest/marketing/parkings/components/ParkingBookingFormModal.tsx' 'ui/src/features/guest/marketing/parkings/components/ParkingLinkedStayConfirm.tsx' 'ui/src/features/guest/marketing/parkings/components/ParkingRegistrationForm.tsx' 'ui/src/features/guest/marketing/parkings/lib/formatParkingLocation.test.ts' 'ui/src/features/guest/marketing/parkings/lib/groupParkingsByLocation.test.ts' 'ui/src/features/guest/marketing/parkings/lib/parkingDimensions.test.ts' 'ui/src/features/guest/marketing/parkings/lib/parkingLinkStay.test.ts' 'ui/src/features/guest/marketing/parkings/lib/parkingListEntries.test.ts' 'ui/src/features/guest/marketing/parkings/lib/parkingRegistrationSchema.test.ts' 'ui/src/features/guest/marketing/parkings/lib/parkingRegistrationSteps.test.ts' 'ui/src/features/guest/marketing/parkings/lib/parkingRequestEntryCopy.test.ts' 'ui/src/features/guest/marketing/parkings/lib/parkingTypeLabel.test.ts' 'ui/src/features/guest/marketing/parkings/lib/parkingsQuery.test.ts' 'ui/src/features/guest/marketing/properties/components/property-detail/GuestBookingFormModal.tsx' 'ui/src/features/guest/marketing/properties/lib/groupPropertiesByDevelopment.test.ts' 'ui/src/features/guest/marketing/properties/lib/groupPropertiesByLocation.test.ts' 'ui/src/features/guest/marketing/properties/lib/mapPublicPropertyDetail.test.ts' 'ui/src/features/guest/marketing/properties/lib/propertiesQuery.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): add super-admin routes and parking payouts
EOF
)"
git add -- 'ui/src/features/guest/marketing/properties/lib/propertyLandingSections.test.ts' 'ui/src/features/guest/marketing/properties/lib/propertyMapEmbed.test.ts' 'ui/src/features/guest/marketing/properties/lib/propertyOverviewStats.test.ts' 'ui/src/features/guest/marketing/shared/components/MarketingFooter.tsx' 'ui/src/features/guest/marketing/shared/components/MarketingMoreSheet.tsx' 'ui/src/features/guest/marketing/shared/lib/listingFilterChips.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingFilterMotion.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingMapLayout.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingMapMarkers.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingPlacement.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingQueryParams.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingScrollSearchEasing.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingScrollSearchPaths.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingSearchDefaultLocation.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingSearchFields.test.ts' 'ui/src/features/guest/marketing/shared/lib/listingSearchPreferType.test.ts' 'ui/src/features/guest/marketing/shared/lib/locationSlug.test.ts' 'ui/src/features/guest/marketing/showcase/components/ShowcasePreviewMockBanner.tsx' 'ui/src/features/guest/marketing/showcase/lib/mapShowcaseData.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseBrandPalette.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseChrome.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseEditorStyleFields.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseHeaderChrome.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseHeroEyebrow.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseHeroLayout.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseHostContent.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseLocation.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseMediaPalette.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseMobileMenuTypography.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcasePalettePreview.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcasePaletteSurfaces.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcasePaths.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcasePresetPalettes.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseScroll.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseSectionLayout.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): update team rbac catalog and permissions
EOF
)"
git add -- 'ui/src/features/guest/marketing/showcase/lib/showcaseSpotlight.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseStyleConfig.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseThemeTokens.test.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseTypographyScale.test.ts' 'ui/src/features/guest/marketing/showcase/templates/atlas/AtlasSections.tsx' 'ui/src/features/guest/marketing/showcase/templates/verso/VersoSections.tsx' 'ui/src/features/guest/marketing/shared/lib/marketingSiteLinks.test.ts' 'ui/src/features/guest/marketing/shared/lib/marketingSiteLinks.ts' 'ui/src/features/guest/pay-parking/components/PayParkingSections.tsx' 'ui/src/features/guest/pay-parking/lib/payParkingHelpers.test.ts' 'ui/src/features/guest/sd-form/components/SdFormReviewSection.tsx' 'ui/src/features/guest/sd-form/lib/api.ts' 'ui/src/features/guest/sd-form/lib/guestReviewFeedbackTags.test.ts' 'ui/src/features/guest/sd-form/lib/sdFormSchema.test.ts' 'ui/src/features/guest/sd-form/lib/voucher.test.ts' 'ui/src/features/guest/sd-form/lib/voucherRevealMotion.test.ts' 'ui/src/features/guest/sd-form/lib/voucherRevealStyle.test.ts' 'ui/src/features/guest/sd-form/pages/SdFormPage.tsx' 'ui/src/features/guest/search/lib/amenityLabels.test.ts' 'ui/src/features/guest/search/lib/geolocation.test.ts' 'ui/src/features/guest/search/lib/mapSearchSummaries.test.ts' 'ui/src/features/guest/search/lib/searchFilterParams.test.ts' 'ui/src/features/guest/search/lib/searchParams.test.ts' 'ui/src/features/guest/stay-guide/lib/mapStayGuideData.test.ts' 'ui/src/features/guest/stay-guide/lib/stayGuideConfig.test.ts' 'ui/src/features/guest/stay-guide/lib/stayGuideContent.test.ts' '.agent/skills/forms/SKILL.md' '.agent/skills/mobile-responsive/SKILL.md' '.agent/skills/plans-and-permissions/SKILL.md' 'CLAUDE.md' 'opencode.json' 'package.json' 'ui/.env.example' 'ui/e2e/features/account/shared/guestFavoritesHarness.ts' 'ui/e2e/features/admin/adminApprovalsSmoke.spec.ts'
c

MSG="$(cat <<'EOF'
test(e2e): add unsaved changes guard infrastructure
EOF
)"
git add -- 'ui/e2e/features/admin/shared/adminApprovalsHarness.ts' 'ui/e2e/features/auth/legacyRouteRedirectSmoke.spec.ts' 'ui/e2e/features/dashboard/dashboardModulesSmoke.spec.ts' 'ui/e2e/features/marketing/marketingAiGenerate.spec.ts' 'ui/e2e/features/onboarding/shared/onboardingHarness.ts' 'ui/e2e/features/org/orgHubSmoke.spec.ts' 'ui/e2e/features/plans/org/orgPlanCheckout.spec.ts' 'ui/e2e/features/plans/shared/orgPlanCheckoutHarness.ts' 'ui/e2e/features/plans/shared/orgPlanDowngradeHarness.ts' 'ui/e2e/features/plans/shared/orgPlanHarnessShared.ts' 'ui/e2e/features/team/shared/propertyTeamRbacHarness.ts' 'ui/e2e/shared/authSeam.ts' 'ui/e2e/shared/layoutAssertions.ts' '.agent/skills/unsaved-changes-guard/SKILL.md' 'ui/e2e/features/admin/adminAiConsole.spec.ts' 'ui/e2e/features/admin/shared/adminAiConsoleHarness.ts' 'ui/e2e/features/analytics/aiReviewPlaybook.spec.ts' 'ui/e2e/features/analytics/shared/aiReviewHarness.ts' 'ui/e2e/features/org/orgAiSettingsToggleOnly.spec.ts' 'ui/e2e/features/org/unsavedChangesGuard.spec.ts' 'ui/e2e/features/plans/gates/featureGates.spec.ts' 'ui/e2e/features/plans/org/orgPlanReviewDialog.spec.ts' 'ui/e2e/features/plans/org/orgPlansCardsCompare.spec.ts' 'ui/e2e/features/plans/public/forHostsPricing.spec.ts' 'ui/e2e/features/plans/shared/planPageAssertions.ts' 'ui/e2e/features/plans/shared/tierGateMocks.ts' 'ui/e2e/features/team/propertyTeamPermissionCatalog.spec.ts' 'scripts/README.md' 'scripts/dev/batch-commit-run-20.sh' 'scripts/dev/check-unbounded-select.sh' 'scripts/dev/seed-analytics-demo-data.sql' 'scripts/dev/check-plan-catalog.ts' 'supabase/functions/ai-platform-property-settings/index.ts' 'supabase/functions/ai-platform-settings/index.ts' 'supabase/functions/analytics-ai-review/index.ts'
c

MSG="$(cat <<'EOF'
feat(supabase): extend app loader and error boundaries
EOF
)"
git add -- 'supabase/functions/analytics-ai-review-cron/index.ts' 'supabase/functions/analytics-org-summary/index.ts' 'supabase/functions/apply-org-plan-downgrade/index.ts' 'supabase/functions/dashboard-assistant-chat/index.ts' 'supabase/functions/dashboard-assistant-conversations/index.ts' 'supabase/functions/dashboard-assistant-feedback/index.ts' 'supabase/functions/dashboard-assistant-global-settings/index.ts' 'supabase/functions/dashboard-assistant-settings/index.ts' 'supabase/functions/dashboard-stats/index.ts' 'supabase/functions/generate-marketing-media/index.ts' 'supabase/functions/get-org-superhost-progress/index.ts' 'supabase/functions/list-activity-log/index.ts' 'supabase/functions/marketing-generations/index.ts' 'supabase/functions/org-subscriptions-admin/index.ts' 'supabase/functions/smart-pricing-apply/index.ts' 'supabase/functions/smart-pricing-preview/index.ts' 'supabase/functions/smart-pricing-settings/index.ts' 'supabase/functions/super-admin-ai-limits/index.ts' 'supabase/functions/super-admin-ai-usage/index.ts' 'supabase/functions/tests/planFeatureGateErrors.test.ts' 'supabase/functions/tests/planFeatureGateResolution.test.ts' 'supabase/functions/tests/teamPermissionGates.test.ts' 'supabase/functions/tests/teamPermissionGatesLocal.integration_test.ts' 'supabase/functions/upload-marketing-generation-reference/index.ts' 'supabase/functions/voice-receptionist-settings/index.ts' 'supabase/migrations/20261316124000_ai_limit_profiles.sql' 'supabase/migrations/20261316125000_team_permissions_plan_coverage_leaves.sql' 'supabase/config.toml' 'supabase/functions/_shared/activityLog.ts' 'supabase/functions/_shared/aiUsageService.ts' 'supabase/functions/_shared/analyticsAiReview.ts' 'supabase/functions/_shared/analyticsService.ts' 'supabase/functions/_shared/dashboardAssistantContext.ts' 'supabase/functions/_shared/dashboardAssistantSettings.ts' 'supabase/functions/_shared/dashboardAssistantStreamEvents.ts'
c

MSG="$(cat <<'EOF'
feat(supabase): update e2e smoke and plan gate specs
EOF
)"
git add -- 'supabase/functions/_shared/marketingGenerationBudget.ts' 'supabase/functions/_shared/marketingGenerationFeatureConfig.ts' 'supabase/functions/_shared/orgAuth.ts' 'supabase/functions/_shared/orgTeamPermissions.ts' 'supabase/functions/_shared/parkingTeamPermissions.ts' 'supabase/functions/_shared/planEntitlements.ts' 'supabase/functions/_shared/planFeatures_test.ts' 'supabase/functions/_shared/propertySettingsCloneGroups.ts' 'supabase/functions/_shared/propertyTeamPermissions.ts' 'supabase/functions/_shared/propertyTeamTemplates.ts' 'supabase/functions/_shared/superAdminVerification.ts' 'supabase/functions/_shared/superhostMetrics_test.ts' 'supabase/functions/_shared/voiceReceptionistService.ts' 'supabase/functions/_shared/aiLimitAdmin.ts' 'supabase/functions/_shared/aiLimitAdmin_test.ts' 'supabase/functions/_shared/aiLimitGuard.ts' 'supabase/functions/_shared/aiLimitGuard_test.ts' 'supabase/functions/_shared/aiLimitResolver.ts' 'supabase/functions/_shared/aiLimitResolver_test.ts' 'supabase/functions/_shared/analyticsAiReviewPeriod.ts' 'supabase/functions/_shared/analyticsAiReviewPeriod_test.ts' 'supabase/functions/_shared/dashboardAssistantBriefing.ts' 'supabase/functions/_shared/dashboardAssistantBriefing_test.ts' 'supabase/functions/_shared/dashboardAssistantConversations.ts' 'supabase/functions/_shared/dashboardAssistantConversations_test.ts' 'supabase/functions/_shared/dashboardAssistantNavigationTools.ts' 'supabase/functions/_shared/dashboardAssistantNavigationTools_test.ts' 'supabase/functions/_shared/dashboardAssistantRoutes.ts' 'supabase/functions/_shared/dashboardAssistantRoutes_test.ts' 'supabase/functions/_shared/dashboardStatsScope.ts' 'supabase/functions/_shared/teamPermissionLeaves_test.ts' 'supabase/functions/_shared/userUiPreferences.ts' 'supabase/functions/_shared/userUiPreferences_test.ts' '.claude/README.md' '.claude/hooks/remind-mobile-native-on-ui-edit.sh'
c

MSG="$(cat <<'EOF'
chore(tooling): add edge ai limits and team permission tests
EOF
)"
git add -- '.claude/hooks/session-mobile-native-ui-reminder.sh' '.claude/settings.local.json' '.cursor/hooks/remind-mobile-native-on-ui-edit.sh' '.cursor/hooks/session-mobile-native-ui-reminder.sh' '.cursor/rules/README.md' '.cursor/rules/admin-auth.mdc' '.cursor/rules/forms.mdc' '.cursor/rules/mobile-responsive.mdc' '.cursor/rules/plans-and-permissions.mdc' '.cursor/rules/testing.mdc' '.claude/skills/unsaved-changes-guard' '.cursor/rules/unsaved-changes.mdc' '.cursor/skills/unsaved-changes-guard' 'ui/src/components/branding/AppLoader.tsx' 'ui/src/components/error/AppErrorBoundary.tsx' 'ui/src/components/forms/FieldLabel.tsx' 'ui/src/components/parking/ParkingFlowStatusIcon.tsx' 'ui/src/components/branding/appLoaderHost.ts' 'ui/src/components/branding/appLoaderWordmark.test.ts' 'ui/src/components/branding/appLoaderWordmark.ts' 'ui/src/components/error/RouteErrorFallback.tsx' 'ui/src/components/error/RuntimeErrorFallback.tsx' 'ui/src/components/forms/ReadonlySlugField.tsx' 'ui/src/components/forms/UnsavedChangesDialog.tsx' 'ui/src/components/forms/UnsavedChangesProvider.tsx' 'ui/src/components/forms/unsavedChangesContext.ts' 'ui/src/components/routing/AppShell.tsx' 'ui/src/components/wizard/WizardModalActions.tsx' 'ui/src/hooks/useGuardedClose.ts' 'ui/src/hooks/useUnsavedChangesGuard.ts' 'ui/src/index.css' 'ui/src/lib/charts/chartPalette.test.ts' 'ui/src/lib/charts/chartStyles.test.ts' 'ui/src/lib/chat/chatMessageActions.test.ts' 'ui/src/lib/chat/chatMessageFormat.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): sync docs route guides and architecture
EOF
)"
git add -- 'ui/src/lib/chat/chatReplyStatus.test.ts' 'ui/src/lib/chat/chatThreadSearch.test.ts' 'ui/src/lib/chat/focusComposerInput.test.ts' 'ui/src/lib/chat/useChatReadReceiptSync.test.ts' 'ui/src/lib/chat/useChatThreadSearch.test.ts' 'ui/src/lib/chat/useChatTyping.test.ts' 'ui/src/lib/date/manilaPeriod.test.ts' 'ui/src/lib/date/navigation.test.ts' 'ui/src/lib/e2e/adminSession.test.ts' 'ui/src/lib/e2e/guestSession.test.ts' 'ui/src/lib/favicon.test.ts' 'ui/src/lib/google-maps/locationLabel.test.ts' 'ui/src/lib/google-maps/useGoogleMapsLoader.test.ts' 'ui/src/lib/media/imageOptimization.test.ts' 'ui/src/lib/media/mediaTelemetry.test.ts' 'ui/src/lib/media/optimizeQueue.test.ts' 'ui/src/lib/media/uploadLimitsTest.ts' 'ui/src/lib/pageTitle.test.ts' 'ui/src/lib/parking/parkingFlowCopy.test.ts' 'ui/src/lib/parking/parkingFlowMotion.test.ts' 'ui/src/lib/pdf/pdfFinanceTotals.test.ts' 'ui/src/lib/pdf/pdfFonts.test.ts' 'ui/src/lib/pdf/pdfFonts.ts' 'ui/src/lib/pdf/pdfFormatters.test.ts' 'ui/src/lib/pdf/pdfReportLayout.test.ts' 'ui/src/lib/pdf/pdfScopeLabel.test.ts' 'ui/src/lib/pdf/pdfStatusColors.test.ts' 'ui/src/lib/pdf/pdfStatusColors.ts' 'ui/src/lib/pdf/pdfTheme.test.ts' 'ui/src/lib/pdf/usePdfBrandColor.test.ts' 'ui/src/lib/platformBranding.test.ts' 'ui/src/lib/posthog/analyticsMode.test.ts' 'ui/src/lib/posthog/bootstrapTelemetry.test.ts' 'ui/src/lib/posthog/capture.test.ts' 'ui/src/lib/posthog/context.test.ts'
c

MSG="$(cat <<'EOF'
feat(ui): update agent tooling rules and scripts
EOF
)"
git add -- 'ui/src/lib/posthog/env.test.ts' 'ui/src/lib/posthog/guestFormAnalytics.test.ts' 'ui/src/lib/pwa/capabilities.test.ts' 'ui/src/lib/pwa/installPrompt.test.ts' 'ui/src/lib/pwa/offlineQueryAllowlist.test.ts' 'ui/src/lib/pwa/pwaTelemetry.test.ts' 'ui/src/lib/pwa/queryPersister.test.ts' 'ui/src/lib/pwa/share.test.ts' 'ui/src/lib/pwa/swRegistration.test.ts' 'ui/src/lib/pwa/syncEngine.test.ts' 'ui/src/lib/pwa/useRegisterSW.test.ts' 'ui/src/lib/query/refetchWhenVisible.test.ts' 'ui/src/lib/sanitizeHtml.test.ts' 'ui/src/lib/security/antiSpamRequest.test.ts' 'ui/src/lib/security/antiSpamResponse.test.ts' 'ui/src/lib/sentry/client.ts' 'ui/src/lib/statusToneColors.test.ts' 'ui/src/lib/theme/applyBrandCssVariables.test.ts' 'ui/src/lib/theme/brandColor.test.ts' 'ui/src/lib/theme/brandColorPresets.test.ts' 'ui/src/lib/theme/hsvColor.test.ts' 'ui/src/lib/theme/photoBrandColor.test.ts' 'ui/src/lib/theme/preferences.test.ts' 'ui/src/lib/validation/adminSettings.test.ts' 'ui/src/lib/unsavedChanges/registry.test.ts' 'ui/src/lib/unsavedChanges/registry.ts' 'ui/src/main.tsx' 'ui/src/utils/format/bookingDisplay.test.ts' 'ui/src/utils/format/parkingStayDisplay.test.ts'
c

echo "batch-commit-run-30 done"
